(function(){
  "use strict";
  const S=window.OneLineStore,I=S.icon,root=document.getElementById('admin-app');
  const emptyForm=(audience)=>({audience:audience||'retail',type:'Simple',name:'',category:S.getCategories()[0]?.name||'',subcategory:'',price:'',mrp:'',stock:'',description:'',image:'assets/crew-tee.webp',optionTitle:'Option',optionsText:'',colorsText:'',sizesText:'',colorImages:{},optionImages:{},stockByColor:{},stockByOption:{},subItem:false});
  const state={tab:'overview',products:S.getProducts(),b2bProducts:S.getB2BProducts(),categories:S.getCategories(),orders:S.getOrders(),prints:S.getPrints(),delivery:S.getDelivery(),settings:S.getSettings(),menu:false,drawer:false,editingId:null,editingAudience:'retail',form:emptyForm('retail'),categoryDraft:{name:'',subcategories:'',image:'assets/crew-tee.webp'},toast:''};

  function toast(text){state.toast=text;render();setTimeout(()=>{if(state.toast===text){state.toast='';render();}},2200);}
  function shell(content){return '<div class="admin-shell"><aside class="admin-sidebar '+(state.menu?'open':'')+'"><div class="admin-logo"><img src="one-line-mark.svg" alt=""><div><b>One-Line</b><small>ADMIN</small></div></div><button class="admin-close" data-action="menu">'+I('close')+'</button><nav>'+nav('overview','home','Overview')+nav('products','package','Ready-made')+nav('categories','sliders','Categories')+nav('b2b','lock','B2B products')+nav('custom','sparkle','Customizer')+nav('delivery','truck','Delivery')+nav('settings','sliders','Settings')+'</nav><div class="admin-side-links"><a href="index.html">Customer site '+I('external')+'</a><a href="receiver.html">Order receiving '+I('external')+'</a></div></aside><section class="admin-main"><header class="admin-top"><button class="admin-menu" data-action="menu">'+I('menu')+'</button><div><span>ONE-LINE CONTROL</span><h1>'+titleForTab()+'</h1></div><div class="admin-header-actions"><a href="receiver.html" aria-label="Order board">'+I('orders')+'</a></div></header><div class="admin-content"><main>'+content+'</main></div></section>'+drawer()+(state.toast?'<div class="toast">'+S.esc(state.toast)+'</div>':'')+'</div>';}
  function nav(tab,icon,label){return '<button data-tab="'+tab+'" class="'+(state.tab===tab?'active':'')+'">'+I(icon)+'<span>'+label+'</span></button>';}
  function titleForTab(){return ({overview:'Overview',products:'Ready-made catalogue',categories:'Categories & subcategories',b2b:'B2B catalogue',custom:'Customizer settings',delivery:'Delivery settings',settings:'Business settings'})[state.tab]||'Admin';}
  function panelHead(kicker,title,button){return '<div class="panel-head"><div><span>'+kicker+'</span><h2>'+title+'</h2></div>'+(button||'')+'</div>';}

  function overview(){
    const retail=state.products.length,b2b=state.b2bProducts.length,open=state.orders.filter(o=>!['Delivered','Cancelled'].includes(o.status)).length;
    return '<div class="admin-overview"><section class="admin-hero-panel"><div><span>CATALOGUE CONTROL</span><h1>Keep the customer side simple.</h1><p>Manage ready-made products, category images, WellOne-style variants, B2B-only stock and customizer print rules from one place.</p></div><button class="admin-primary" data-action="new-retail">'+I('plus')+' Add ready-made item</button></section><div class="admin-metrics"><article><span>READY-MADE ITEMS</span><b>'+retail+'</b></article><article><span>B2B ONLY ITEMS</span><b>'+b2b+'</b></article><article><span>CATEGORIES</span><b>'+state.categories.length+'</b></article><article><span>OPEN ORDERS</span><b>'+open+'</b></article></div><section class="admin-panel">'+panelHead('WORKFLOW','Product structures')+'<div class="admin-structure-grid"><article><b>Simple</b><p>One product image, one price and one stock pool.</p></article><article><b>One Option</b><p>Use size, pack, ml or another single option. Each option can have its own image and stock.</p></article><article><b>Colour + Option</b><p>Upload one image for each colour. Every size under that colour automatically uses the same colour image.</p></article></div></section></div>';
  }

  function productRows(products,audience){
    if(!products.length)return '<div class="empty-admin"><b>No products yet</b><span>Add the first item to this catalogue.</span></div>';
    return '<div class="admin-products-list">'+products.map(p=>'<article><img src="'+S.esc(p.image)+'" alt=""><div><small>'+S.esc(p.category)+' · '+S.esc(p.subcategory)+'</small><b>'+S.esc(p.name)+'</b><span>'+S.esc(humanType(p.type))+' · '+Number(p.stock||0)+' stock</span></div>'+(audience==='retail'?'<strong>'+S.money(p.price)+'</strong>':'<strong class="b2b-admin-badge">ASK PRICE</strong>')+'<button data-edit-product="'+S.esc(p.id)+'" data-audience="'+audience+'">'+I('edit')+' Edit</button><button class="danger-icon" data-delete-product="'+S.esc(p.id)+'" data-audience="'+audience+'">'+I('trash')+'</button></article>').join('')+'</div>';
  }
  function humanType(type){return type==='Colour + Option'?'Colour with sizes/options':type==='One Option'?'One selectable option':'Simple item';}
  function products(){return '<section class="admin-panel">'+panelHead('CUSTOMER CATALOGUE','Ready-made products','<button class="admin-primary" data-action="new-retail">'+I('plus')+' Add product</button>')+'<p class="panel-intro">Customers can order these products directly. They cannot edit/customize them from the product page; customization is handled through the dedicated designer or WhatsApp enquiry.</p>'+productRows(state.products,'retail')+'</section>';}
  function b2b(){return '<section class="admin-panel">'+panelHead('BUSINESS-ONLY CATALOGUE','B2B products','<button class="admin-primary" data-action="new-b2b">'+I('plus')+' Add B2B item</button>')+'<p class="panel-intro">These products never appear in the normal customer catalogue. The B2B page hides prices and sends Ask for Price enquiries to WhatsApp.</p>'+productRows(state.b2bProducts,'b2b')+'</section>';}

  function categories(){
    return '<div class="category-admin-page"><section class="admin-panel add-category-panel">'+panelHead('CATALOGUE ORGANISATION','Create category')+'<div class="category-create-grid"><label>Name<input data-cat-new="name" value="'+S.esc(state.categoryDraft.name)+'" placeholder="e.g. Hoodies"></label><label>Subcategories <small>comma separated</small><input data-cat-new="subcategories" value="'+S.esc(state.categoryDraft.subcategories)+'" placeholder="Zip, Pullover, Oversized"></label><div class="admin-image-field"><span>Category image</span><img src="'+S.esc(state.categoryDraft.image)+'" alt=""><button data-action="new-category-image">'+I('upload')+' Upload image</button><input type="file" accept="image/*" data-new-category-file hidden></div><button class="admin-primary" data-action="add-category">'+I('plus')+' Create category</button></div></section><section class="admin-panel">'+panelHead('CUSTOMER CATEGORY CARDS','Categories & images')+'<div class="category-manage-grid">'+state.categories.map((c,i)=>'<article data-category-card="'+S.esc(c.id||c.name)+'"><div class="category-admin-image"><img src="'+S.esc(c.image||'assets/crew-tee.webp')+'" alt=""><button data-category-upload="'+i+'">'+I('upload')+' Change image</button><input type="file" accept="image/*" data-category-file="'+i+'" hidden></div><label>Category name<input data-category-name="'+i+'" value="'+S.esc(c.name)+'"></label><label>Short line<input data-category-sub="'+i+'" value="'+S.esc(c.sub||'')+'"></label><label>Subcategories <small>comma separated</small><textarea data-category-subcats="'+i+'">'+S.esc((c.subcategories||[]).join(', '))+'</textarea></label><div class="category-card-actions"><button data-action="save-categories">Save</button><button class="danger-text" data-delete-category="'+i+'">Delete</button></div></article>').join('')+'</div></section></div>';
  }

  function custom(){return '<div class="settings-grid"><section class="admin-panel">'+panelHead('PRINTING TYPES','Customizer printing rules')+'<p class="panel-intro">Sublimation stays visible in the selector but is automatically disabled when the customer chooses a dark garment.</p><div class="print-admin">'+state.prints.map((p,i)=>'<article><span>'+String(i+1).padStart(2,'0')+'</span><div><b>'+S.esc(p.name)+'</b><small>'+S.esc(p.note)+'</small>'+(p.lightOnly?'<em>LIGHT COLOURS ONLY</em>':'')+'</div><label>₹ <input data-print-price="'+i+'" type="number" value="'+Number(p.price||0)+'"></label></article>').join('')+'</div><button class="admin-primary" data-action="save-prints">Save print pricing</button></section><section class="admin-panel">'+panelHead('CUSTOMIZER','Garment colours')+'<div class="colour-admin-grid">'+Object.entries(S.palette).map(([name,hex])=>'<div><span style="background:'+hex+'"></span><b>'+name+'</b><small>'+(S.isDarkColor(name)?'Dark · sublimation disabled':'Light / medium')+'</small></div>').join('')+'</div></section></div>';}

  function delivery(){return '<section class="admin-panel">'+panelHead('CHECKOUT','Delivery methods','<button class="admin-primary" data-action="add-delivery">'+I('plus')+' Add method</button>')+'<div class="setting-list delivery-list">'+state.delivery.map((d,i)=>'<article>'+I(d.name.toLowerCase().includes('pickup')?'package':d.name.toLowerCase().includes('bus')?'box':'truck')+'<div><b>'+S.esc(d.name)+'</b><small>'+S.esc(d.note)+'</small></div><label class="switch"><input data-delivery-toggle="'+i+'" type="checkbox" '+(d.active?'checked':'')+'><span></span></label><button data-remove-delivery="'+i+'">'+I('trash')+'</button></article>').join('')+'</div></section>';}

  function settings(){return '<div class="settings-grid"><section class="admin-panel">'+panelHead('WHATSAPP','Fast enquiry')+'<div class="admin-form-stack"><label>WhatsApp number <small>country code + number, numbers only</small><input data-setting="whatsapp" value="'+S.esc(state.settings.whatsapp)+'" placeholder="e.g. 919876543210"></label><p>If this is left blank, WhatsApp opens the contact chooser with the enquiry message ready.</p><button class="admin-primary" data-action="save-settings">Save WhatsApp setting</button></div></section><section class="admin-panel">'+panelHead('B2B LOGIN','Single business login')+'<div class="admin-form-stack"><label>Login ID<input data-setting="b2bLoginId" value="'+S.esc(state.settings.b2bLoginId)+'"></label><label>Password<input data-setting="b2bPassword" value="'+S.esc(state.settings.b2bPassword)+'"></label><p>This static version stores the single B2B login in browser storage. Connect it to your backend before public production use.</p><button class="admin-primary" data-action="save-settings">Save B2B login</button></div></section></div>';}

  function pickerSelect(name,value,items){return '<select name="'+name+'">'+items.map(x=>'<option value="'+S.esc(x)+'" '+(String(x)===String(value)?'selected':'')+'>'+S.esc(x)+'</option>').join('')+'</select>';}
  function imageUploader(label,src,attr){return '<div class="drawer-image-upload"><span>'+label+'</span><img src="'+S.esc(src||'assets/crew-tee.webp')+'" alt=""><button type="button" '+attr+'>'+I('upload')+' Upload image</button></div>';}
  function variantEditor(){
    const f=state.form;
    if(f.type==='Simple')return '<div class="variant-help">Simple item uses the main image, one stock value and one selling price.</div>';
    if(f.type==='One Option'){
      const opts=f.optionsText.split(',').map(x=>x.trim()).filter(Boolean);
      return '<div class="form-section variant-builder"><div class="variant-builder-title"><div><label>Option label<input name="optionTitle" value="'+S.esc(f.optionTitle||'Option')+'" placeholder="Size / Pack / ml"></label><label>Options <small>comma separated</small><input name="optionsText" value="'+S.esc(f.optionsText)+'" placeholder="S, M, L, XL"></label></div><button type="button" data-action="refresh-variants">Prepare option rows</button></div>'+(opts.length?'<div class="option-variant-list">'+opts.map((o,i)=>'<article><b>'+S.esc(o)+'</b>'+imageUploader('Optional image',f.optionImages[o]||f.image,'data-option-image-button="'+S.esc(o)+'"')+'<input type="file" accept="image/*" data-option-image-file="'+S.esc(o)+'" hidden><label>Stock<input type="number" min="0" data-option-stock="'+S.esc(o)+'" value="'+Number(f.stockByOption[o]??f.stock??0)+'"></label></article>').join('')+'</div>':'<p class="variant-help">Enter the options, then click Prepare option rows.</p>')+'</div>';
    }
    const colors=f.colorsText.split(',').map(x=>x.trim()).filter(Boolean),sizes=f.sizesText.split(',').map(x=>x.trim()).filter(Boolean);
    return '<div class="form-section variant-builder"><div class="variant-builder-title colour-variant-title"><div><label>Colours <small>comma separated</small><input name="colorsText" value="'+S.esc(f.colorsText)+'" placeholder="Black, White, Navy"></label><label>Sizes / options <small>comma separated</small><input name="sizesText" value="'+S.esc(f.sizesText)+'" placeholder="S, M, L, XL"></label></div><button type="button" data-action="refresh-variants">Prepare colour groups</button></div><div class="variant-rule-note">'+I('check')+' <span><b>One image per colour.</b> That image is automatically used for every size inside that colour group.</span></div>'+(colors.length&&sizes.length?'<div class="colour-group-editor">'+colors.map(c=>'<article><div class="colour-group-head"><span class="admin-colour-dot" style="background:'+(S.palette[c]||'#ddd')+'"></span><b>'+S.esc(c)+'</b></div>'+imageUploader('Colour image',f.colorImages[c]||f.image,'data-colour-image-button="'+S.esc(c)+'"')+'<input type="file" accept="image/*" data-colour-image-file="'+S.esc(c)+'" hidden><div class="size-stock-grid">'+sizes.map(s=>'<label><span>'+S.esc(s)+'</span><input type="number" min="0" data-colour-stock="'+S.esc(c)+'" data-size="'+S.esc(s)+'" value="'+Number(f.stockByColor[c]?.[s]??f.stock??0)+'"></label>').join('')+'</div></article>').join('')+'</div>':'<p class="variant-help">Enter colours and sizes, then click Prepare colour groups. Each colour gets one image and all its sizes reuse it.</p>')+'</div>';
  }

  function drawer(){
    if(!state.drawer)return '';const f=state.form,cats=state.categories.map(c=>c.name),isB2B=f.audience==='b2b';
    return '<div class="overlay receiver-overlay"><aside class="admin-drawer enhanced-product-drawer"><div class="drawer-head"><div><span>'+(state.editingId?'EDIT ITEM':'NEW ITEM')+'</span><h2>'+(isB2B?'B2B product':'Ready-made product')+'</h2></div><button data-action="close-drawer">'+I('close')+'</button></div><form data-product-form><div class="form-section"><label>Product structure</label><div class="type-cards">'+['Simple','One Option','Colour + Option'].map(t=>'<button type="button" data-form-type="'+t+'" class="'+(f.type===t?'active':'')+'"><span>'+(f.type===t?I('check'):'')+'</span><b>'+humanType(t)+'</b><small>'+(t==='Simple'?'One image and one stock pool':t==='One Option'?'One selectable size/pack/ml option':'One image per colour, many sizes per colour')+'</small></button>').join('')+'</div></div><div class="form-section form-grid"><label class="text-field">Product name<input required name="name" value="'+S.esc(f.name)+'"></label><label class="text-field">Category'+pickerSelect('category',f.category,cats)+'</label><label class="text-field">Subcategory<input required name="subcategory" value="'+S.esc(f.subcategory)+'" list="admin-subcategories"><datalist id="admin-subcategories">'+state.categories.find(c=>c.name===f.category)?.subcategories?.map(s=>'<option value="'+S.esc(s)+'"></option>').join('')+'</datalist></label><label class="text-field">Total stock <small>used as default for new variant rows</small><input required name="stock" type="number" min="0" value="'+S.esc(f.stock)+'"></label>'+(!isB2B?'<label class="text-field">MRP<input required name="mrp" type="number" min="0" value="'+S.esc(f.mrp)+'"></label><label class="text-field">Selling price<input required name="price" type="number" min="0" value="'+S.esc(f.price)+'"></label>':'')+'<label class="text-field full">Description<textarea name="description">'+S.esc(f.description)+'</textarea></label></div><div class="form-section">'+imageUploader('Main / fallback product image',f.image,'data-main-image-button')+'<input data-main-image-file hidden type="file" accept="image/*"></div>'+variantEditor()+'<div class="drawer-actions"><button type="button" data-action="close-drawer">Cancel</button><button class="admin-primary" type="submit">'+(state.editingId?'Update product':'Save product')+'</button></div></form></aside></div>';
  }

  function captureForm(){
    const form=root.querySelector('[data-product-form]');if(!form)return;const fd=new FormData(form);
    ['name','category','subcategory','price','mrp','stock','description','optionTitle','optionsText','colorsText','sizesText'].forEach(k=>{if(fd.has(k))state.form[k]=String(fd.get(k)||'');});
    root.querySelectorAll('[data-colour-stock]').forEach(el=>{const c=el.dataset.colourStock,s=el.dataset.size;state.form.stockByColor[c]=state.form.stockByColor[c]||{};state.form.stockByColor[c][s]=Number(el.value||0);});
    root.querySelectorAll('[data-option-stock]').forEach(el=>state.form.stockByOption[el.dataset.optionStock]=Number(el.value||0));
  }
  function formFromProduct(p,audience){
    const n=S.normalizeProduct(p),f=emptyForm(audience);Object.assign(f,{type:n.type,name:n.name,category:n.category,subcategory:n.subcategory,price:n.price??'',mrp:n.mrp??'',stock:n.stock??'',description:n.description||'',image:n.image||'assets/crew-tee.webp',optionTitle:n.optionTitle||'Option'});
    if(n.type==='One Option'){f.optionsText=n.options.map(o=>o.value).join(', ');n.options.forEach(o=>{f.optionImages[o.value]=o.image||n.image;f.stockByOption[o.value]=Number(o.stock||0);});}
    if(n.type==='Colour + Option'){f.colorsText=n.colorGroups.map(g=>g.color).join(', ');f.sizesText=[...new Set(n.colorGroups.flatMap(g=>g.sizes.map(s=>typeof s==='string'?s:s.value)))].join(', ');n.colorGroups.forEach(g=>{f.colorImages[g.color]=g.image||n.image;f.stockByColor[g.color]={};g.sizes.forEach(s=>f.stockByColor[g.color][typeof s==='string'?s:s.value]=Number(typeof s==='string'?n.stock:s.stock||0));});}
    return f;
  }
  function buildProduct(){
    const f=state.form,base={id:state.editingId||Date.now(),audience:f.audience,name:f.name.trim(),category:f.category,subcategory:f.subcategory.trim()||'General',type:f.type,image:f.image||'assets/crew-tee.webp',stock:Number(f.stock||0),description:f.description.trim()||'Catalogue product.'};
    if(f.audience==='retail'){base.price=Number(f.price||0);base.mrp=Number(f.mrp||0);}else{base.price=0;base.mrp=0;}
    if(f.type==='Simple'){base.colors=[];base.sizes=['Default'];}
    else if(f.type==='One Option'){const opts=f.optionsText.split(',').map(x=>x.trim()).filter(Boolean);base.optionTitle=f.optionTitle||'Option';base.options=opts.map(o=>({value:o,stock:Number(f.stockByOption[o]??f.stock??0),image:f.optionImages[o]||f.image}));base.sizes=opts;base.colors=[];base.stock=base.options.reduce((n,o)=>n+o.stock,0)||Number(f.stock||0);}
    else {const colors=f.colorsText.split(',').map(x=>x.trim()).filter(Boolean),sizes=f.sizesText.split(',').map(x=>x.trim()).filter(Boolean);base.colorGroups=colors.map(c=>({color:c,image:f.colorImages[c]||f.image,sizes:sizes.map(s=>({value:s,stock:Number(f.stockByColor[c]?.[s]??f.stock??0)}))}));base.colors=colors;base.sizes=sizes;base.stock=base.colorGroups.reduce((sum,g)=>sum+g.sizes.reduce((n,s)=>n+s.stock,0),0)||Number(f.stock||0);}
    return base;
  }

  function compressImage(file,done){
    if(!file||!file.type.startsWith('image/'))return;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const scale=Math.min(1,1000/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);done(canvas.toDataURL('image/webp',.82));};img.src=String(reader.result);};reader.readAsDataURL(file);
  }
  function saveCategories(){
    root.querySelectorAll('[data-category-name]').forEach(el=>{const i=Number(el.dataset.categoryName);state.categories[i].name=el.value.trim()||state.categories[i].name;});
    root.querySelectorAll('[data-category-sub]').forEach(el=>state.categories[Number(el.dataset.categorySub)].sub=el.value.trim());
    root.querySelectorAll('[data-category-subcats]').forEach(el=>state.categories[Number(el.dataset.categorySubcats)].subcategories=el.value.split(',').map(x=>x.trim()).filter(Boolean));
    S.save('custom-store-categories',state.categories);toast('Categories saved');
  }

  function render(){
    state.products=S.getProducts();state.b2bProducts=S.getB2BProducts();state.categories=S.getCategories();state.orders=S.getOrders();state.prints=S.getPrints();state.delivery=S.getDelivery();state.settings=S.getSettings();
    const content=({overview,products,categories,b2b,custom,delivery,settings})[state.tab]();root.innerHTML=shell(content);bind();
  }

  function bind(){
    root.querySelectorAll('[data-tab]').forEach(x=>x.addEventListener('click',()=>{state.tab=x.dataset.tab;state.menu=false;state.drawer=false;render();}));
    root.querySelectorAll('[data-action]').forEach(x=>x.addEventListener('click',()=>{
      const a=x.dataset.action;
      if(a==='menu'){state.menu=!state.menu;render();}
      else if(a==='new-retail'){state.form=emptyForm('retail');state.drawer=true;state.editingId=null;state.editingAudience='retail';render();}
      else if(a==='new-b2b'){state.form=emptyForm('b2b');state.drawer=true;state.editingId=null;state.editingAudience='b2b';render();}
      else if(a==='close-drawer'){state.drawer=false;state.editingId=null;render();}
      else if(a==='refresh-variants'){captureForm();render();}
      else if(a==='save-prints'){root.querySelectorAll('[data-print-price]').forEach(el=>state.prints[Number(el.dataset.printPrice)].price=Number(el.value||0));S.save('custom-store-print-types',state.prints);toast('Print pricing saved');}
      else if(a==='add-delivery'){state.delivery.push({name:'Local delivery',note:'Delivery details confirmed with customer',active:true});S.save('custom-store-delivery',state.delivery);render();}
      else if(a==='save-settings'){root.querySelectorAll('[data-setting]').forEach(el=>state.settings[el.dataset.setting]=el.value.trim());S.save('custom-store-settings',state.settings);toast('Settings saved');}
      else if(a==='new-category-image'){root.querySelector('[data-new-category-file]')?.click();}
      else if(a==='add-category'){const name=root.querySelector('[data-cat-new="name"]')?.value.trim(),subs=root.querySelector('[data-cat-new="subcategories"]')?.value.split(',').map(x=>x.trim()).filter(Boolean)||[];if(!name){toast('Enter a category name');return;}state.categories.push({id:'cat-'+Date.now(),name,sub:subs.slice(0,3).join(' · '),code:String(state.categories.length+1).padStart(2,'0'),tone:['acid','ink','blue','clay','paper'][state.categories.length%5],image:state.categoryDraft.image||'assets/crew-tee.webp',subcategories:subs});S.save('custom-store-categories',state.categories);state.categoryDraft={name:'',subcategories:'',image:'assets/crew-tee.webp'};render();}
      else if(a==='save-categories')saveCategories();
    }));
    root.querySelectorAll('[data-form-type]').forEach(x=>x.addEventListener('click',()=>{captureForm();state.form.type=x.dataset.formType;render();}));
    root.querySelectorAll('[data-edit-product]').forEach(x=>x.addEventListener('click',()=>{const audience=x.dataset.audience,list=audience==='b2b'?state.b2bProducts:state.products,p=list.find(p=>String(p.id)===String(x.dataset.editProduct));if(!p)return;state.editingId=p.id;state.editingAudience=audience;state.form=formFromProduct(p,audience);state.drawer=true;render();}));
    root.querySelectorAll('[data-delete-product]').forEach(x=>x.addEventListener('click',()=>{const audience=x.dataset.audience,key=audience==='b2b'?'custom-store-b2b-products':'custom-store-products',list=(audience==='b2b'?state.b2bProducts:state.products).filter(p=>String(p.id)!==String(x.dataset.deleteProduct));S.save(key,list);render();}));
    root.querySelectorAll('[data-category-upload]').forEach(x=>x.addEventListener('click',()=>root.querySelector('[data-category-file="'+x.dataset.categoryUpload+'"]')?.click()));
    root.querySelectorAll('[data-category-file]').forEach(x=>x.addEventListener('change',()=>compressImage(x.files?.[0],data=>{state.categories[Number(x.dataset.categoryFile)].image=data;S.save('custom-store-categories',state.categories);render();})));
    const newCatFile=root.querySelector('[data-new-category-file]');if(newCatFile)newCatFile.addEventListener('change',()=>compressImage(newCatFile.files?.[0],data=>{state.categoryDraft.image=data;render();}));
    root.querySelectorAll('[data-cat-new]').forEach(x=>x.addEventListener('input',()=>state.categoryDraft[x.dataset.catNew]=x.value));
    root.querySelectorAll('[data-delete-category]').forEach(x=>x.addEventListener('click',()=>{state.categories.splice(Number(x.dataset.deleteCategory),1);S.save('custom-store-categories',state.categories);render();}));
    root.querySelectorAll('[data-delivery-toggle]').forEach(x=>x.addEventListener('change',()=>{state.delivery[Number(x.dataset.deliveryToggle)].active=x.checked;S.save('custom-store-delivery',state.delivery);}));
    root.querySelectorAll('[data-remove-delivery]').forEach(x=>x.addEventListener('click',()=>{state.delivery.splice(Number(x.dataset.removeDelivery),1);S.save('custom-store-delivery',state.delivery);render();}));
    const form=root.querySelector('[data-product-form]');
    if(form){
      form.addEventListener('input',e=>{if(e.target.matches('[name="stock"],[data-colour-stock],[data-option-stock]'))captureForm();});
      form.addEventListener('submit',e=>{e.preventDefault();captureForm();const f=state.form;if(!f.name.trim()||!f.category||!f.subcategory.trim()){toast('Enter product name, category and subcategory');return;}if(f.audience==='retail'&&(!Number(f.price)||!Number(f.mrp))){toast('Enter MRP and selling price');return;}if(f.type==='One Option'&&!f.optionsText.split(',').map(x=>x.trim()).filter(Boolean).length){toast('Add at least one option');return;}if(f.type==='Colour + Option'&&(!f.colorsText.split(',').map(x=>x.trim()).filter(Boolean).length||!f.sizesText.split(',').map(x=>x.trim()).filter(Boolean).length)){toast('Add colours and sizes/options');return;}const product=buildProduct(),key=f.audience==='b2b'?'custom-store-b2b-products':'custom-store-products',list=f.audience==='b2b'?state.b2bProducts.slice():state.products.slice();const i=list.findIndex(p=>String(p.id)===String(product.id));if(i>=0)list[i]=product;else list.unshift(product);S.save(key,list);state.drawer=false;state.editingId=null;state.form=emptyForm(f.audience);state.tab=f.audience==='b2b'?'b2b':'products';render();});
      const mainBtn=root.querySelector('[data-main-image-button]'),mainFile=root.querySelector('[data-main-image-file]');if(mainBtn&&mainFile){mainBtn.addEventListener('click',()=>mainFile.click());mainFile.addEventListener('change',()=>compressImage(mainFile.files?.[0],data=>{captureForm();state.form.image=data;render();}));}
      root.querySelectorAll('[data-colour-image-button]').forEach(btn=>btn.addEventListener('click',()=>root.querySelector('[data-colour-image-file="'+CSS.escape(btn.dataset.colourImageButton)+'"]')?.click()));
      root.querySelectorAll('[data-colour-image-file]').forEach(file=>file.addEventListener('change',()=>compressImage(file.files?.[0],data=>{captureForm();state.form.colorImages[file.dataset.colourImageFile]=data;render();})));
      root.querySelectorAll('[data-option-image-button]').forEach(btn=>btn.addEventListener('click',()=>root.querySelector('[data-option-image-file="'+CSS.escape(btn.dataset.optionImageButton)+'"]')?.click()));
      root.querySelectorAll('[data-option-image-file]').forEach(file=>file.addEventListener('change',()=>compressImage(file.files?.[0],data=>{captureForm();state.form.optionImages[file.dataset.optionImageFile]=data;render();})));
    }
  }

  window.addEventListener('storage',render);window.addEventListener('one-line-change',render);render();
})();
