(function(){
"use strict";
const S=window.OneLineStore,I=S.icon,root=document.getElementById("app");
const B2B=document.body.dataset.portalRole==="b2b";
const state={screen:B2B?"catalog":"home",filters:{},productQty:1,galleryImage:"",products:S.getProducts().filter(p=>p.active),categories:S.categoriesForCustomer(),cart:S.getCart(),orders:S.getOrders(),settings:S.getSettings(),category:"All",query:"",selected:null,color:"",size:"",fabricId:"",menu:false,toast:"",legal:"",callback:false,callbackProduct:"",checkoutStep:1,details:{name:"",phone:"",address:"",business:""},delivery:"Courier",payment:"Cash on delivery",orderPlaced:false,orderReference:"",installPrompt:null,b2b:S.getSession("b2b"),loginError:""};
const legalCopy={
  "About":["We create dependable custom apparel for individuals, teams, institutions and businesses.","Our catalogue combines ready-made essentials with print-ready garments, uniforms, sportswear, belts and identification tags."],
  "Terms & Conditions":["Product colours may vary slightly across screens and production batches. Customized orders enter production only after design and price confirmation.","Customers must confirm spelling, artwork placement, sizes, fabric, quantities and print method before approval."],
  "Privacy Policy":["Customer details are used only to prepare the order, arrange delivery and provide support.","Uploaded artwork should contain only material the customer has permission to reproduce."],
  "Shipping & Returns":["Delivery timing depends on stock, quantity and customization. The team confirms the schedule before production.","Customized items cannot be returned after production begins unless defective or different from the approved design."]
};
const totalQty=()=>state.cart.reduce((n,x)=>n+Number(x.qty||0),0);
const subtotal=()=>state.cart.reduce((n,x)=>n+Number(x.price||0)*Number(x.qty||0),0);
const account=()=>B2B?S.getSession("b2b"):null;
const visibleProducts=()=>state.products.filter(p=>!p.customSection&&S.categoryVisible(p)&&(B2B?p.b2bEnabled:p.customerVisible&&!p.b2bOnly));
function refresh(){state.products=S.getProducts().filter(p=>p.active);state.categories=S.categoriesForCustomer();state.settings=S.getSettings();state.orders=S.getOrders();if(state.selected){state.selected=state.products.find(p=>String(p.id)===String(state.selected.id))||null;}}
function logo(compact){return '<div class="brand" aria-label="'+S.esc(state.settings.storeName)+'"><img class="brand-mark" src="one-line-mark.svg" alt="">'+(compact?'':'<span class="brand-copy"><b>'+S.esc(state.settings.storeName)+'</b><small>'+S.esc(state.settings.tagline)+'</small></span>')+'</div>';}
function showToast(t){state.toast=t;render();setTimeout(()=>{if(state.toast===t){state.toast="";render();}},2400);}
function go(s,replace){if(s==="b2b"&&!B2B){location.href="b2b.html";return;}if(B2B&&!["catalog","product","b2b"].includes(s))s="catalog";state.screen=s;state.menu=false;state.legal="";if(window.history){const method=replace?"replaceState":"pushState";window.history[method]({screen:s},"","#"+s);}window.scrollTo({top:0,behavior:"smooth"});render();}
function goBack(){if(window.history&&window.history.length>1)window.history.back();else go("home",true);}
function saveCart(){if(state.cart.length)S.save(S.KEYS.cart,state.cart);else localStorage.removeItem(S.KEYS.cart);}
function addCart(item,navigate){const same=state.cart.find(x=>x.key===item.key);if(same)same.qty+=item.qty||1;else state.cart.push(item);saveCart();navigate?go("cart"):showToast("Added to your cart");}
function filtered(){return visibleProducts().filter(p=>S.matches(p,{...state.filters,categories:state.category==='All'?(state.filters.categories||[]):[state.category]},state.query));}
function openProduct(id){const p=visibleProducts().find(x=>String(x.id)===String(id));if(!p)return;state.selected=p;const first=S.availableRows(p)[0]||p.variants[0];state.color=first?.colour||p.colors?.[0]||'';state.size=first?.size||p.sizes?.[0]||'';state.productQty=1;state.galleryImage='';go('product');}
function chosenFabric(){return S.getFabrics().find(x=>x.id===state.fabricId)||{name:"Standard",price:0,description:""};}
function currentPrice(){return S.productPrice(state.selected,state.color,state.size);}
function colourProductImage(p,c,detail){const src=detail?(state.galleryImage||S.productImage(p,c,'front',state.size)):S.productImage(p,c);return '<div class="colour-product-image '+(detail?'detail-colour-image':'')+'"><img src="'+S.esc(src)+'" alt="'+S.esc(p.name)+'" class="product-image" loading="lazy"></div>';}
function productCard(p){const enquiry=B2B||p.askForPrice||p.enquiryOnly,discount=!enquiry&&p.mrp>p.price?Math.round((p.mrp-p.price)/p.mrp*100):0;return '<article class="product-card" data-open-product="'+p.id+'" tabindex="0" role="button" aria-label="View '+S.esc(p.name)+'"><div class="product-image-wrap">'+colourProductImage(p,p.colors?.[0]||'',false)+(discount?'<span class="discount-tag">-'+discount+'%</span>':'')+'<button class="quick-add" data-open-product="'+p.id+'" aria-label="Open product">'+I('arrow')+'</button></div><div class="product-info"><p>'+S.esc(p.subcategory)+'</p><h3>'+S.esc(p.name)+'</h3><div class="price-row"><strong>'+(enquiry?'Ask For Price':S.money(p.price))+'</strong>'+(!enquiry&&p.mrp>p.price?'<s>'+S.money(p.mrp)+'</s>':'')+'</div><div class="stock-line"><span></span>'+(S.availableRows(p).length?'Available':'Out of stock')+'</div></div></article>';}
function header(){return '<div class="announcement"><span>'+S.esc(account()?account().business+" · B2B catalogue":"CUSTOM APPAREL · BULK PRICING · DESIGN PREVIEW")+'</span><b>'+S.esc(state.settings.supportText)+'</b></div><header class="site-header"><button class="mobile-menu" data-action="menu">'+I("menu")+'</button><button class="logo-button" data-go="home">'+logo(false)+'</button><nav class="'+(state.menu?"open":"")+'"><button data-go="home">Home</button><button data-go="catalog">Shop</button><button data-go="customize">Customize</button><button data-go="b2b">'+(account()?"B2B account":"B2B login")+'</button><button data-go="orders">Orders</button></nav><div class="header-actions"><label class="header-search">'+I("search")+'<input data-header-search placeholder="Search products"></label><button class="install-link" data-action="callback">'+I("phone")+'<span>Call me</span></button><button data-go="cart" class="bag-link">'+I("bag")+'<span>'+totalQty()+'</span></button></div></header>';}
function footer(){return '<footer><div class="footer-main">'+logo(false)+'<p>Custom apparel, uniforms, sportswear and accessories with clear product and print pricing.</p><div><b>SHOP</b><button data-go="catalog">All products</button><button data-go="customize">Custom designer</button><button data-go="b2b">B2B access</button></div><div><b>INFORMATION</b>'+Object.keys(legalCopy).map(x=>'<button data-legal="'+x+'">'+x+'</button>').join("")+'</div><div><b>BUSINESS</b><a href="'+S.whatsappUrl()+'" target="_blank" rel="noopener">WhatsApp support</a><button data-action="callback">Request a callback</button></div></div><div class="footer-bottom"><span>© 2026 '+S.esc(state.settings.storeName)+'</span><span>Clear pricing · Exact design · Managed production</span></div></footer>';}
function bottom(){return '<nav class="mobile-bottom"><button data-go="home" class="'+(state.screen==="home"?"active":"")+'">'+I("home")+'Home</button><button data-go="catalog" class="'+(state.screen==="catalog"?"active":"")+'">'+I("search")+'Shop</button><button data-go="customize">'+I("plus")+'Create</button><button data-go="b2b" class="'+(state.screen==="b2b"?"active":"")+'">'+I("users")+'B2B</button><button data-go="cart" class="'+(state.screen==="cart"?"active":"")+'">'+I("bag")+'<i>'+totalQty()+'</i>Cart</button></nav>';}
function customStudioSection(){const p=S.getProducts().find(x=>x.active&&x.customSection);return '<section class="custom-studio-section section-wrap"><div class="custom-studio-copy"><span class="eyebrow">CUSTOMIZABLE</span><h2>Create one from scratch.</h2><p>Choose a garment colour, add your own text or image, then pick the printing method. Ready-made products stay separate.</p><button class="primary" data-go="customize">Open custom editor '+I("arrow")+'</button></div><div class="custom-studio-visual"><img src="'+S.esc(p?.customizerImage||"assets/crew-tee.webp")+'" alt="Customizable apparel"><span>TEXT · IMAGE · COLOUR</span></div></section>';}
function home(){const available=visibleProducts();return '<main class="screen screen-enter"><section class="hero"><div class="hero-copy"><span class="eyebrow">MADE FOR YOUR NAME, TEAM OR BUSINESS</span><h1>Wear your<br><em>own idea.</em></h1><p>Shop ready-made products normally, or use the dedicated Customizable section to add your own text, image and garment colour.</p><div class="hero-actions"><button class="primary" data-go="customize">Start customizing '+I("arrow")+'</button><button class="secondary" data-go="catalog">Shop ready-made</button></div><div class="hero-proof"><span>'+I("shield")+' Exact preview saved</span><span>'+I("package")+' Separate element pricing</span></div></div><div class="hero-visual"><div class="hero-grid-label">CUSTOM PRODUCT STUDIO</div><div class="hero-product-orbit"><div class="orbit-ring"></div><img src="assets/crew-tee.webp" alt="Custom T-shirt"><div class="hero-brand-badge"><img src="one-line-mark.svg" alt=""><span>BUILD YOUR OWN</span></div></div><div class="floating-tool tool-a">'+I("type")+'<span>Multiple text</span></div><div class="floating-tool tool-b">'+I("image")+'<span>Multiple images</span></div><div class="floating-tool tool-c">'+I("sparkle")+'<span>Colour + print</span></div><button class="visual-cta" data-go="customize"><span>OPEN DESIGNER</span>'+I("arrow")+'</button></div></section>'+categoriesSection()+customStudioSection()+processSection()+'<section class="products-section section-wrap"><div class="section-heading"><div><span class="eyebrow">READY TO ORDER</span><h2>Popular essentials.</h2></div><button data-go="catalog">See catalogue '+I("arrow")+'</button></div><div class="product-grid">'+available.slice(0,4).map(productCard).join("")+'</div></section><section class="bulk-banner section-wrap"><div><span>B2B / TEAMS / INSTITUTIONS</span><h2>Better pricing for bigger orders.</h2><p>Browse the wholesale catalogue and ask for a quote on WhatsApp.</p></div><button data-go="b2b">Open B2B '+I("arrow")+'</button></section></main>';}
function categoriesSection(){return '<section class="category-section section-wrap"><div class="section-heading"><div><span class="eyebrow">SHOP BY CATEGORY</span><h2>Everything you can make.</h2></div><button data-go="catalog">View all '+I("arrow")+'</button></div><div class="category-grid">'+state.categories.map(c=>'<button class="category-block '+c.tone+'" data-category="'+S.esc(c.name)+'"><span class="category-code">'+c.code+'</span><div class="category-photo"><img src="'+S.esc(c.image||"assets/category-tshirts.webp")+'" alt="'+S.esc(c.name)+'" loading="lazy"></div><div><h3>'+S.esc(c.name)+'</h3><p>'+S.esc(c.sub)+'</p></div>'+I("arrow")+'</button>').join("")+'</div></section>';}
function processSection(){const rows=[["sliders","Choose","Select the customizable item, garment colour and size."],["move","Create","Add several texts and images on every print side."],["sparkle","Price","Each print element has its own editable price."],["truck","Receive","Order online or continue through WhatsApp."]];return '<section class="process-section"><div class="section-wrap"><span class="eyebrow light">CUSTOM ORDER PROCESS</span><h2>From blank product<br>to finished piece.</h2><div class="process-grid">'+rows.map((x,i)=>'<article><b>0'+(i+1)+'</b>'+I(x[0])+'<h3>'+x[1]+'</h3><p>'+x[2]+'</p></article>').join("")+'</div><button class="acid-button" data-go="customize">Create now '+I("arrow")+'</button></div></section>';}
function catalog(){const list=filtered();return '<main class="catalog-page section-wrap screen screen-enter"><div class="catalog-title"><div><span class="eyebrow">CATALOGUE / '+String(list.length).padStart(2,"0")+'</span><h1>'+(state.category==="All"?"Shop all products":S.esc(state.category))+'</h1></div><button class="filter-button" data-action="focus-filters">'+I("sliders")+' Filters '+I("chevron")+'</button></div><div class="catalog-tools"><label>'+I("search")+'<input data-catalog-search value="'+S.esc(state.query)+'" placeholder="Search products, categories or keywords"></label><div class="category-pills"><button class="'+(state.category==="All"?"active":"")+'" data-category="All">All</button>'+state.categories.map(c=>'<button class="'+(state.category===c.name?"active":"")+'" data-category="'+S.esc(c.name)+'">'+S.esc(c.name)+'</button>').join("")+'</div></div>'+(list.length?'<div class="product-grid catalog-grid">'+list.map(productCard).join("")+'</div>':'<div class="empty-state">'+I("search")+'<h2>No matching items</h2><p>Try another category or search term.</p><button data-action="clear-filters">Clear filters</button></div>')+'</main>';}
function qualityOptions(p){return S.getFabrics().filter(x=>x.active&&(p.allowedFabricIds||[]).includes(x.id)).map(f=>'<button data-fabric="'+f.id+'" class="'+(state.fabricId===f.id?"active":"")+'"><span><b>'+S.esc(f.name)+'</b><small>'+S.esc(f.description)+'</small></span><strong>+'+S.money(f.price)+'</strong></button>').join("");}
function productV2(){
 const p=state.selected;if(!p||p.customSection)return catalog();const stock=S.productStock(p,state.color,state.size),enquiry=B2B||p.askForPrice||p.enquiryOnly,canBuy=!enquiry&&stock>0,selectedImage=S.productImage(p,state.color,'front',state.size),gallery=[...new Set([selectedImage,...(p.gallery||[])].filter(Boolean))];
 return `<main class="product-page section-wrap screen screen-enter"><button class="back-button" data-go="catalog">${I('back')} Back to products</button><div class="product-detail modern-product-detail"><div class="product-gallery-column"><div class="product-detail-image">${colourProductImage(p,state.color,true)}</div>${gallery.length>1?`<div class="product-gallery-thumbs">${gallery.map(src=>`<button data-gallery-src="${S.esc(src)}" class="${(state.galleryImage||selectedImage)===src?'active':''}" aria-label="View product image"><img src="${S.esc(src)}" alt=""></button>`).join('')}</div>`:''}</div><div class="product-detail-copy"><span class="eyebrow">${S.esc(p.category)}${p.subcategory?' / '+S.esc(p.subcategory):''}</span><h1>${S.esc(p.name)}</h1><div class="product-code">ID: ${S.esc(p.sku||p.id)}</div><div class="detail-price">${enquiry?'<strong>Ask For Price</strong><span>Send your selection for a '+(B2B?'wholesale':'personal')+' quote</span>':`<strong>${S.money(currentPrice())}</strong>${p.mrp>currentPrice()?`<s>${S.money(p.mrp)}</s>`:''}<span>${S.esc(state.settings.taxLabel)}</span>`}</div><p>${S.esc(p.description)}</p>
 ${p.colors.length?`<div class="selection-block"><label>Colour <b>${S.esc(state.color)}</b></label><div class="colour-options">${p.colors.map(c=>`<button class="${state.color===c?'active':''}" data-product-color="${S.esc(c)}"><span style="background:${S.esc(S.colourValue(p,c))}"></span>${S.esc(c)}</button>`).join('')}</div></div>`:''}
 ${p.sizes.length?`<div class="selection-block"><label>${S.esc(p.optionName||'Size')} <b>${S.esc(state.size)}</b></label><div class="size-options">${p.sizes.map(size=>`<button class="${state.size===size?'active':''} ${S.productStock(p,state.color,size)?'':'unavailable-option'}" data-product-size="${S.esc(size)}" aria-label="${S.esc(size)}${S.productStock(p,state.color,size)?'':' — unavailable'}">${S.esc(size)}</button>`).join('')}</div></div>`:''}
 <div class="stock-availability ${stock?'':'out'}">${stock?stock+' available':'Currently out of stock'}</div><label class="product-quantity">Quantity<input data-product-quantity type="number" min="1" max="999" step="1" value="${state.productQty||1}" inputmode="numeric"></label><div class="product-action-grid">${enquiry?`<a class="primary wide" data-enquiry href="${S.whatsappUrl(S.enquiryMessage(p,state.color,state.size,state.productQty,B2B))}" target="_blank" rel="noopener">${I('phone')} ${B2B?'Ask For Price':'Enquire on WhatsApp'}</a>`:`<button class="primary wide" data-action="buy-now" ${canBuy?'':'disabled'}>Buy now ${I('arrow')}</button><a class="secondary wide" data-enquiry href="${S.whatsappUrl(S.enquiryMessage(p,state.color,state.size,state.productQty,false))}" target="_blank" rel="noopener">Product enquiry</a>`}</div>${B2B?'':`<div class="ready-custom-enquiry"><span>${I('sparkle')}</span><div><b>Need this customized?</b><small>Send your logo or text requirement to our team.</small></div><a target="_blank" rel="noopener" href="${S.whatsappUrl('Hello, I want to customize '+p.name+' ('+p.sku+'). Please contact me.')}">Enquire for customization ${I('arrow')}</a></div>`}</div></div></main>`;
}
function cartItem(item){const thumb=item.customDesign?S.designPreview(item.customDesign,"front","cart-design-preview"):'<img src="'+S.esc(item.image||"assets/crew-tee.webp")+'" alt="">';return '<article class="cart-item">'+thumb+'<div class="cart-item-info"><span>'+(item.custom?"CUSTOM DESIGN":"READY-MADE")+'</span><h3>'+S.esc(item.name)+'</h3><p>'+[item.color,item.size,item.detail].filter(Boolean).map(S.esc).join(" · ")+'</p>'+(item.customDesign?'<small class="design-spec">'+item.customDesign.elementCount+' separately priced print elements · '+S.designedSurfaces(item.customDesign).length+' sides</small>':'')+'<strong>'+S.money(item.price)+'</strong></div><div class="qty-control"><button data-qty="-1" data-key="'+item.key+'">'+I("minus")+'</button><span>'+item.qty+'</span><button data-qty="1" data-key="'+item.key+'">'+I("plus")+'</button></div><button class="remove-item" data-remove-key="'+item.key+'">'+I("trash")+'</button></article>';}
function cart(){const disc=S.discountFor(totalQty(),account());return '<main class="cart-page section-wrap screen screen-enter"><div class="catalog-title"><div><span class="eyebrow">YOUR SELECTION</span><h1>Cart <sup>'+totalQty()+'</sup></h1></div><button class="back-button" data-go="catalog">'+I("back")+' Continue shopping</button></div>'+(state.cart.length?'<div class="cart-layout"><section class="cart-list">'+state.cart.map(cartItem).join("")+'</section><aside class="order-summary"><span class="eyebrow">ORDER SUMMARY</span><div><span>Subtotal</span><b>'+S.money(subtotal())+'</b></div>'+(disc?'<div class="bulk-saving"><span>Bulk / B2B rate</span><b>'+disc+'% active</b></div>':'')+'<div><span>Delivery</span><b>Confirmed next</b></div><hr><div class="summary-total"><span>Estimated total</span><strong>'+S.money(subtotal())+'</strong></div><button class="primary wide" data-action="checkout">Proceed to checkout '+I("arrow")+'</button><a class="secondary wide whatsapp-cart" href="'+S.whatsappUrl(cartMessage())+'" target="_blank" rel="noopener">'+I("phone")+' Continue on WhatsApp</a><p>'+I("shield")+' Stock is checked before confirmation.</p></aside></div>':'<div class="empty-state cart-empty">'+I("bag")+'<h2>Your cart is empty</h2><p>Choose a ready-made item or create your design.</p><div><button class="primary" data-go="customize">Start customizing</button><button class="secondary" data-go="catalog">Browse products</button></div></div>')+'</main>';}
function cartMessage(){return "Hello, I want to enquire about this order:\n"+state.cart.map(x=>"- "+x.name+" | "+x.color+" | "+x.size+" | Qty "+x.qty+" | "+S.money(x.price*x.qty)).join("\n")+"\nEstimated total: "+S.money(subtotal());}
function checkout(){if(state.orderPlaced)return success();const deliveries=S.getDelivery().filter(x=>x.active);return '<main class="checkout-page section-wrap screen screen-enter"><div class="checkout-head"><button class="back-button" data-go="cart">'+I("back")+' Back</button>'+logo(true)+'<span>Order review '+I("shield")+'</span></div><div class="checkout-steps two-steps"><span class="'+(state.checkoutStep>=1?"active":"")+'"><b>1</b>Details</span><i></i><span class="'+(state.checkoutStep>=2?"active":"")+'"><b>2</b>Delivery</span></div><div class="checkout-layout"><section class="checkout-card">'+(state.checkoutStep===1?'<div><span class="eyebrow">STEP 01</span><h1>Your details</h1><p>Enter the contact and delivery information.</p><form class="checkout-form" data-checkout-form><label>Full name<input required name="name" value="'+S.esc(state.details.name||account()?.name||"")+'"></label><label>Phone number<input required name="phone" type="tel" minlength="10" pattern="[0-9 +()-]{10,15}" value="'+S.esc(state.details.phone||"")+'"></label><label class="full">Delivery address<textarea required name="address" rows="4">'+S.esc(state.details.address||"")+'</textarea></label><label class="full">Business / institution <small>Optional</small><input name="business" value="'+S.esc(state.details.business||account()?.business||"")+'"></label></form><button class="primary wide" data-action="delivery-step">Choose delivery '+I("arrow")+'</button></div>':'<div><span class="eyebrow">STEP 02</span><h1>Delivery & confirmation</h1><p>The production team will verify artwork, stock and schedule.</p><div class="checkout-choice"><label>Delivery method</label>'+deliveries.map(x=>'<button class="'+(state.delivery===x.name?"active":"")+'" data-delivery="'+S.esc(x.name)+'">'+I(x.name.includes("pickup")?"package":x.name.includes("Bus")?"box":"truck")+'<span><b>'+S.esc(x.name)+'</b><small>'+S.esc(x.note)+'</small></span>'+(state.delivery===x.name?I("check"):'')+'</button>').join("")+'</div><div class="checkout-choice"><label>Payment</label><button class="active">'+I("card")+'<span><b>'+S.esc(state.settings.allowCOD?"Cash / payment after confirmation":"Payment after confirmation")+'</b><small>Final payment instructions are shared after review.</small></span>'+I("check")+'</button></div><button class="primary wide" data-action="submit-order">Confirm order request '+I("arrow")+'</button></div>')+'</section><aside class="mini-summary"><span>ORDER TOTAL</span><strong>'+S.money(subtotal())+'</strong><p>'+totalQty()+' pieces · '+S.esc(state.delivery)+'</p><hr>'+state.cart.map(x=>'<div><span>'+S.esc(x.name)+' × '+x.qty+'</span><b>'+S.money(x.price*x.qty)+'</b></div>').join("")+'</aside></div></main>';}
function success(){return '<main class="checkout-page section-wrap screen screen-enter"><div class="order-success"><div class="success-icon">'+I("check")+'</div><span class="eyebrow">ORDER REQUEST CONFIRMED</span><h1>Your order is saved.</h1><p>The production team can see every item, side, text, artwork, placement, garment colour and print method.</p><div class="success-order"><span>Order reference</span><b>#'+state.orderReference+'</b></div><div><button class="primary" data-action="view-order">View order</button><a class="secondary" href="'+S.whatsappUrl("Hello, I placed order "+state.orderReference+". Please confirm it.")+'" target="_blank">Send on WhatsApp</a></div></div></main>';}
function orderItem(item){const previews=item.customDesign?'<div class="design-surface-gallery">'+S.designedSurfaces(item.customDesign).map(face=>'<figure>'+S.designPreview(item.customDesign,face)+'<figcaption>'+face.replace("Sleeve"," sleeve")+'</figcaption></figure>').join("")+'</div>':'<img src="'+S.esc(item.image||"assets/crew-tee.webp")+'" alt="">';return '<div class="ordered-item">'+previews+'<div><span>'+(item.custom?"CUSTOMIZED ITEM":"READY-MADE ITEM")+'</span><h3>'+S.esc(item.name)+'</h3><p>'+[item.color,item.size,item.detail,"Qty "+item.qty].filter(Boolean).map(S.esc).join(" · ")+'</p></div><strong>'+S.money(item.price*item.qty)+'</strong></div>';}
function orders(){refresh();return '<main class="customer-orders-page section-wrap screen screen-enter"><div class="catalog-title"><div><span class="eyebrow">ORDER HISTORY</span><h1>My orders</h1></div><button class="back-button" data-go="home">'+I("back")+' Home</button></div><div class="customer-order-list">'+state.orders.map(o=>'<article class="customer-order-card"><div class="customer-order-head"><div><span>ORDER #'+S.esc(o.id)+'</span><h2>'+S.esc(o.status)+'</h2></div><div><small>'+S.timeAgo(o.createdAt)+'</small><strong>'+S.money(o.total)+'</strong></div></div><div class="customer-order-items">'+(o.orderItems?.length?o.orderItems.map(orderItem).join(""):'<div class="legacy-order-note">'+I("package")+'<span><b>'+o.items+' ordered items</b><small>Detailed production files are attached to new orders.</small></span></div>')+'</div><div class="customer-order-foot"><span>'+I("truck")+' '+S.esc(o.delivery)+'</span><span>'+I("card")+' '+S.esc(o.payment)+'</span><span>'+I("map")+' '+S.esc(o.address)+'</span></div></article>').join("")+'</div></main>';}
function b2b(){return `<main class="b2b-page section-wrap"><div class="portal-login customer-login"><div>${I('lock')}<span class="eyebrow">B2B PORTAL</span><h1>Your wholesale catalogue.</h1><p>Browse products, select options and enquire directly on WhatsApp.</p></div><form data-b2b-login><label>Username<input required name="username" autocomplete="username"></label><label>Password<input required name="password" type="password" autocomplete="current-password"></label>${state.loginError?`<p class="login-error" role="alert">${S.esc(state.loginError)}</p>`:''}<button class="primary wide">Sign in</button><small>Ask the store for a business account.</small></form></div></main>`;}
function legal(){return '<div class="overlay"><div class="legal-panel"><button class="close" data-action="close-legal">'+I("close")+'</button><span class="eyebrow">STORE INFORMATION</span><h2>'+S.esc(state.legal)+'</h2>'+(legalCopy[state.legal]||[]).map(x=>'<p>'+S.esc(x)+'</p>').join("")+'</div></div>';}
function callback(){const note=state.callbackProduct?"I need details and a quotation for "+state.callbackProduct+" — "+state.color+", "+state.size+".":"";return '<div class="overlay"><div class="legal-panel callback-panel"><button class="close" data-action="close-callback">'+I("close")+'</button><span class="eyebrow">REQUEST A CALLBACK</span><h2>Let us call you.</h2><p>Share your mobile number. Our team will call about quantity, branding and price.</p><form data-callback-form><label>Name<input required name="name"></label><label>Mobile number<input required name="phone" pattern="[0-9 +()-]{10,15}"></label><label>Requirement<textarea name="note" rows="3" placeholder="Product, quantity or customization">'+S.esc(note)+'</textarea></label><button class="primary wide">Request callback</button></form></div></div>';}
function toast(){return state.toast?'<div class="toast">'+I("check")+S.esc(state.toast)+'</div>':"";}
function contactDock(){return '<a class="floating-contact" data-contact-dock href="'+S.whatsappUrl('Hello, I need help choosing or customizing an item.')+'" target="_blank" rel="noopener" aria-label="Contact us on WhatsApp">'+I("phone")+'<span>WhatsApp</span></a>';}
function bindContactDock(){
 const dock=root.querySelector("[data-contact-dock]");if(!dock)return;
 const key="one-line-contact-position",size=54;
 const limits=()=>{const head=root.querySelector(".site-header,.sub-header"),nav=root.querySelector(".mobile-bottom"),top=Math.max(10,(head?.getBoundingClientRect().bottom||62)+8),navTop=nav&&getComputedStyle(nav).display!=="none"?nav.getBoundingClientRect().top:innerHeight;return{minX:8,maxX:Math.max(8,innerWidth-size-8),minY:top,maxY:Math.max(top,navTop-size-8)};};
 const setPosition=(x,y)=>{const b=limits();dock.style.right="auto";dock.style.bottom="auto";dock.style.left=Math.max(b.minX,Math.min(b.maxX,x))+"px";dock.style.top=Math.max(b.minY,Math.min(b.maxY,y))+"px";};
 try{const saved=JSON.parse(localStorage.getItem(key)||"null");if(saved)setPosition(saved.x*(innerWidth-size),saved.y*(innerHeight-size));}catch(_){}
 let drag=null,moved=false;
 dock.addEventListener("pointerdown",e=>{if(e.button!==undefined&&e.button!==0)return;const r=dock.getBoundingClientRect();drag={dx:e.clientX-r.left,dy:e.clientY-r.top};moved=false;dock.setPointerCapture?.(e.pointerId);dock.classList.add("holding");});
 dock.addEventListener("pointermove",e=>{if(!drag)return;const x=e.clientX-drag.dx,y=e.clientY-drag.dy;if(Math.abs(x-dock.getBoundingClientRect().left)>3||Math.abs(y-dock.getBoundingClientRect().top)>3)moved=true;if(moved){e.preventDefault();dock.classList.add("moving");setPosition(x,y);}});
 const end=e=>{if(!drag)return;dock.releasePointerCapture?.(e.pointerId);dock.classList.remove("holding","moving");if(moved){const r=dock.getBoundingClientRect();localStorage.setItem(key,JSON.stringify({x:r.left/Math.max(1,innerWidth-size),y:r.top/Math.max(1,innerHeight-size)}));}drag=null;};
 dock.addEventListener("pointerup",end);dock.addEventListener("pointercancel",end);dock.addEventListener("click",e=>{if(moved){e.preventDefault();e.stopPropagation();moved=false;}});
}
function page(){return ({home,catalog,product:productV2,cart,checkout,orders,b2b})[state.screen]?.()||home();}
function render(){refresh();if(!B2B&&S.getSession("b2b")){location.replace("b2b.html");return;}if(B2B){if(!state.settings.b2bEnabled){root.innerHTML=b2bHeader()+'<main class="empty-state"><h2>B2B catalogue is currently closed</h2><p>Please contact the store for enquiries.</p></main>';return;}if(!account())state.screen="b2b";else if(!["catalog","product"].includes(state.screen))state.screen="catalog";root.innerHTML='<div class="view-root b2b-view">'+b2bHeader()+page()+'<footer class="b2b-footer">Select your options and enquire on WhatsApp.</footer>'+toast()+'</div>';bind();bindCustomerUpgrade();return;}if(state.screen==="customize"){root.innerHTML='<div id="designer-root"></div>'+contactDock();window.OneLineDesigner.mount(document.getElementById("designer-root"),{product:state.selected?.customSection?state.selected:null,color:state.color,size:state.size,fabricId:"",account:account(),onBack:goBack,onAdd:item=>{addCart(item,false);go("cart");}});bindContactDock();return;}root.innerHTML='<div class="view-root">'+header()+page()+footer()+bottom()+(state.legal?legal():"")+(state.callback?callback():"")+toast()+contactDock()+'</div>';bind();bindCustomerUpgrade();}
function completeOrder(){if(B2B)return;try{const order=S.commitOrder({customer:state.details.business||state.details.name,phone:state.details.phone,total:subtotal(),items:totalQty(),delivery:state.delivery,payment:'Pending confirmation',status:'Confirmed',channel:'Customer',address:state.details.address,orderItems:state.cart},{name:state.details.name,role:'customer'});state.cart=[];saveCart();state.orderPlaced=true;state.orderReference=order.id;render();}catch(error){showToast(error.message);}}

function bind(){
  bindContactDock();
  root.querySelectorAll("[data-go]").forEach(x=>x.addEventListener("click",()=>go(x.dataset.go)));
  root.querySelectorAll("[data-open-product]").forEach(x=>x.addEventListener("click",e=>{e.stopPropagation();openProduct(x.dataset.openProduct);}));
  root.querySelectorAll("[data-category]").forEach(x=>x.addEventListener("click",()=>{state.category=x.dataset.category;state.filters={};go("catalog");}));
  root.querySelectorAll("[data-legal]").forEach(x=>x.addEventListener("click",()=>{state.legal=x.dataset.legal;render();}));
  root.querySelectorAll("[data-product-color]").forEach(x=>x.addEventListener("click",()=>{state.color=x.dataset.productColor;state.galleryImage="";const p=state.selected;if(p.variants.length&&!S.findVariant(p,state.color,state.size))state.size=p.variants.find(v=>v.colour===state.color)?.size||"";render();}));
  root.querySelectorAll("[data-product-size]").forEach(x=>x.addEventListener("click",()=>{state.size=x.dataset.productSize;state.galleryImage="";render();}));
  root.querySelectorAll("[data-fabric]").forEach(x=>x.addEventListener("click",()=>{state.fabricId=x.dataset.fabric;render();}));
  root.querySelectorAll("[data-qty]").forEach(x=>x.addEventListener("click",()=>{const item=state.cart.find(i=>i.key===x.dataset.key),next=Math.max(1,item.qty+Number(x.dataset.qty));if(!item.custom&&S.productStock(state.products.find(p=>p.id===item.productId),item.color,item.size)<next)return showToast("No more stock for this selection");item.qty=next;saveCart();render();}));
  root.querySelectorAll("[data-remove-key]").forEach(x=>x.addEventListener("click",()=>{state.cart=state.cart.filter(i=>i.key!==x.dataset.removeKey);saveCart();render();}));
  root.querySelectorAll("[data-delivery]").forEach(x=>x.addEventListener("click",()=>{state.delivery=x.dataset.delivery;render();}));
  root.querySelector("[data-header-search]")?.addEventListener("change",e=>{state.query=e.target.value;go("catalog");});
  root.querySelector("[data-catalog-search]")?.addEventListener("input",e=>{state.query=e.target.value;render();const n=root.querySelector("[data-catalog-search]");n?.focus();n?.setSelectionRange(state.query.length,state.query.length);});
  root.querySelector("[data-b2b-login]")?.addEventListener("submit",e=>{e.preventDefault();const fd=new FormData(e.target),a=S.authenticate("b2b",fd.get("username"),fd.get("password"));if(!a){state.loginError="Incorrect login or this account is blocked.";render();return;}state.b2b=S.setSession(a);state.loginError="";state.screen="catalog";render();});
  root.querySelector("[data-callback-form]")?.addEventListener("submit",e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.target).entries()),rows=S.getCallbacks();rows.unshift({id:"CB-"+Date.now().toString().slice(-6),productId:state.selected?.id||null,...fd,status:"New",createdAt:new Date().toISOString()});S.save(S.KEYS.callbacks,rows);state.callback=false;state.callbackProduct="";showToast("Callback requested successfully");});
  root.querySelectorAll("[data-action]").forEach(x=>x.addEventListener("click",()=>{
    const a=x.dataset.action;
    if(a==="menu"){state.menu=!state.menu;render();}
    if(a==="callback"){state.callbackProduct="";state.callback=true;render();}
    if(a==="request-product-callback"){state.callbackProduct=state.selected?.name||"";state.callback=true;render();}
    if(a==="go-back")goBack();
    if(a==="close-callback"){state.callback=false;render();}
    if(a==="close-legal"){state.legal="";render();}
    if(a==="focus-filters")OneLineFilters.open(visibleProducts(),{...state.filters,categories:state.category!=="All"?[S.getCategories().find(c=>c.name===state.category)?.id].filter(Boolean):(state.filters.categories||[])},filters=>{state.filters=filters;state.category="All";render();});
    if(a==="clear-filters"){state.category="All";state.query="";state.filters={};render();}
    if(a==="buy-now"){if(B2B)return;const p=state.selected,stock=S.productStock(p,state.color,state.size),n=state.productQty||1,existing=state.cart.filter(i=>String(i.productId)===String(p.id)&&i.color===state.color&&i.size===state.size).reduce((sum,i)=>sum+i.qty,0);if(p.askForPrice||p.enquiryOnly)return;if(stock<n+existing)return showToast("Not enough stock for this selection");addCart({key:[p.id,state.color,state.size].join("-"),productId:p.id,name:p.name,price:currentPrice(),qty:n,image:S.productImage(p,state.color,'front',state.size),color:state.color,size:state.size,detail:"Ready-made",custom:false},false);state.checkoutStep=1;state.orderPlaced=false;go("checkout");}
    if(a==="customize-product"){state.selected=null;go("customize");}
    if(a==="checkout"){if(!state.cart.length)return;state.checkoutStep=1;state.orderPlaced=false;go("checkout");}
    if(a==="delivery-step"){const f=root.querySelector("[data-checkout-form]");if(f?.reportValidity()){state.details=Object.fromEntries(new FormData(f).entries());state.checkoutStep=2;render();}}
    if(a==="submit-order")completeOrder();
    if(a==="view-order"){state.orderPlaced=false;go("orders");}
    if(a==="b2b-logout"){S.setSession(null);state.b2b=null;render();}
  }));
}
function b2bHeader(){return `<header class="site-header b2b-header"><button class="logo-button" data-go="catalog">${logo(false)}</button><div class="b2b-identity"><small>B2B CATALOGUE</small><span>${S.esc(account()?.business||account()?.name||'Business access')}</span></div>${account()?`<button class="secondary" data-action="b2b-logout">${I('logout')} Sign out</button>`:''}</header>`;}
function bindCustomerUpgrade(){
 root.querySelectorAll('[data-gallery-src]').forEach(b=>b.onclick=()=>{state.galleryImage=b.dataset.gallerySrc;render();});
 root.querySelector('[data-product-quantity]')?.addEventListener('input',e=>{state.productQty=Math.min(999,Math.max(1,Math.floor(Number(e.target.value)||1)));root.querySelectorAll('[data-enquiry]').forEach(a=>a.href=S.whatsappUrl(S.enquiryMessage(state.selected,state.color,state.size,state.productQty,B2B)));});
 root.querySelectorAll('.product-card').forEach(p=>p.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openProduct(p.dataset.openProduct);}}));
}

window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.installPrompt=e;});
window.addEventListener("popstate",e=>{state.screen=e.state?.screen||"home";state.menu=false;state.legal="";window.scrollTo({top:0});render();});
window.addEventListener("storage",()=>{refresh();render();});
window.addEventListener("one-line-change",()=>{refresh();});
document.addEventListener("contextmenu",e=>e.preventDefault());
const initial=location.hash.slice(1);if(initial==="b2b"&&!B2B)location.replace("b2b.html");state.screen=B2B?"catalog":(["catalog","customize","cart","orders"].includes(initial)?initial:"home");if(window.history)window.history.replaceState({screen:state.screen},"","#"+state.screen);
render();
})();
