(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const STORAGE='oneline-final-cart-v1';
const surfaces={front:{label:'Front',asset:'assets/tshirt-front.webp'},back:{label:'Back',asset:'assets/tshirt-back.webp'},left:{label:'Left sleeve',asset:'assets/tshirt-sleeve-side.webp'},right:{label:'Right sleeve',asset:'assets/tshirt-sleeve-side.webp'}};
const colors=[['White','#f4f2ec'],['Black','#151517'],['Navy','#1e2b46'],['Royal Blue','#244fba'],['Sky','#7ebbe5'],['Bottle Green','#164d3a'],['Olive','#5c6749'],['Red','#c72e3e'],['Maroon','#7b2637'],['Orange','#e36a2e'],['Yellow','#e2bd37'],['Purple','#633499'],['Pink','#db6e9c'],['Beige','#c7ad84'],['Grey','#75777d']];
const fabrics=[
 {id:'cotton180',name:'Combed Cotton · 180 GSM',price:349,note:'Soft everyday T-shirt fabric with a clean print surface.'},
 {id:'cotton220',name:'Heavy Cotton · 220 GSM',price:449,note:'Thicker premium cotton with a structured fall.'},
 {id:'dryfit',name:'Dry Fit Polyester',price:399,note:'Lightweight quick-dry fabric for teams and active use.'},
 {id:'premium',name:'Premium Bio-washed Cotton',price:529,note:'Soft premium finish with excellent colour retention.'}
];
const prints=[
 {id:'dtf',name:'DTF Print',price:120,note:'Full-colour print suitable for light and dark T-shirts.'},
 {id:'screen',name:'Screen Print',price:90,note:'Durable, economical printing for simple colours.'},
 {id:'embroidery',name:'Embroidery',price:190,note:'Premium stitched finish for names and logos.'},
 {id:'sublimation',name:'Sublimation',price:110,note:'Special print for light colours only.',lightOnly:true}
];
const categories=[
 {name:'T-Shirts',image:'assets/category-tshirts.webp',sub:['Crew Neck','Polo','Oversized']},
 {name:'Shirts',image:'assets/category-shirts.webp',sub:['Formal','Casual','Workwear']},
 {name:'Uniforms',image:'assets/category-uniforms.webp',sub:['School','Office','Industrial','Belts','ID Tags']},
 {name:'Sportswear',image:'assets/category-sportswear.webp',sub:['Jerseys','Training','Teamwear']},
 {name:'Tags & Labels',image:'assets/category-tags-labels.webp',sub:['ID Tags','Woven Labels','Printed Labels']}
];
const products=[
 {id:'p1',name:'Premium Polo T-Shirt',category:'T-Shirts',subcategory:'Polo',price:599,mrp:749,image:'assets/polo-shirt.webp',sizes:['M','L','XL','XXL'],colors:['Black','White','Navy','Maroon'],options:['Regular Fit','Premium'],desc:'Soft pique polo for staff, teams, events and everyday business wear.'},
 {id:'p2',name:'Classic Crew T-Shirt',category:'T-Shirts',subcategory:'Crew Neck',price:449,mrp:599,image:'assets/tshirt-front.webp',sizes:['S','M','L','XL','XXL'],colors:['Black','White','Navy','Red'],options:['Regular Fit','Heavy GSM'],desc:'Clean ready-made crew neck with reinforced neck rib and comfortable everyday fit.'},
 {id:'p3',name:'Performance Team Jersey',category:'Sportswear',subcategory:'Jerseys',price:649,mrp:799,image:'assets/sports-jersey.webp',sizes:['S','M','L','XL'],colors:['Navy','White','Red','Royal Blue'],options:['Quick Dry','Teamwear'],desc:'Breathable team jersey with quick-dry performance fabric.'},
 {id:'p4',name:'Executive Uniform Shirt',category:'Uniforms',subcategory:'Office',price:720,mrp:890,image:'assets/uniform-shirt.webp',sizes:['38','40','42','44'],colors:['White','Sky','Beige'],options:['Full Sleeve','Half Sleeve'],desc:'Easy-care office uniform shirt with a professional structured profile.'},
 {id:'p5',name:'Oxford Work Shirt',category:'Shirts',subcategory:'Workwear',price:790,mrp:949,image:'assets/oxford-shirt.webp',sizes:['38','40','42','44','46'],colors:['White','Sky','Grey'],options:['Regular Fit','Full Sleeve'],desc:'Durable Oxford weave shirt made for workwear and uniform applications.'},
 {id:'p6',name:'School Uniform Belt',category:'Uniforms',subcategory:'Belts',price:180,mrp:240,image:'assets/school-belt.webp',sizes:['28–32','34–38','40–44'],colors:['Navy','Black','Maroon'],options:['Standard Buckle'],desc:'Practical woven belt for school uniforms and institutional supply.'},
 {id:'p7',name:'Student ID Tag',category:'Tags & Labels',subcategory:'ID Tags',price:95,mrp:130,image:'assets/student-id-tag.webp',sizes:['Standard','Large'],colors:['White'],options:['Portrait','Landscape'],desc:'Ready-made identification tag body suitable for student and staff use.'}
];
const state={route:'home',filters:{categories:[],subs:[],sizes:[],options:[]},cart:loadCart(),modal:null,drawer:false,custom:{surface:'front',color:'#6f2dbd',colorName:'Custom Purple',fabric:'cotton180',print:'dtf',size:'M',qty:1,layers:{front:[],back:[],left:[],right:[]},selected:null}};
function loadCart(){try{return JSON.parse(localStorage.getItem(STORAGE)||'[]')}catch{return[]}}
function saveCart(){localStorage.setItem(STORAGE,JSON.stringify(state.cart));renderBadges()}
function cartCount(){return state.cart.reduce((n,x)=>n+Number(x.qty||1),0)}
function toast(msg){let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),1800)}
function isLight(hex){hex=hex.replace('#','');if(hex.length===3)hex=hex.split('').map(x=>x+x).join('');const r=parseInt(hex.slice(0,2),16),g=parseInt(hex.slice(2,4),16),b=parseInt(hex.slice(4,6),16);return (0.2126*r+0.7152*g+0.0722*b)>165}
function shell(content){return `<div class="shell"><header class="topbar"><div class="topbar-inner"><button class="brand" data-route="home" style="border:0;background:transparent;padding:0"><span class="brand-badge">OL</span><span>ONE LINE</span></button><nav class="nav">${navBtn('home','Home')}${navBtn('customize','Customize')}${navBtn('catalog','Ready-made')}${navBtn('cart','Cart',true)}</nav></div></header><main class="page">${content}</main>${bottomNav()}</div>`}
function navBtn(route,label,cart=false){return `<button class="nav-btn ${state.route===route?'active':''} ${cart?'cart-button':''}" data-route="${route}">${label}${cart?`<span class="cart-badge">${cartCount()}</span>`:''}</button>`}
function bottomNav(){return `<nav class="bottom-nav"><button data-route="home" class="${state.route==='home'?'active':''}"><b>⌂</b>Home</button><button data-route="customize" class="${state.route==='customize'?'active':''}"><b>✦</b>Customize</button><button data-route="catalog" class="${state.route==='catalog'?'active':''}"><b>▦</b>Ready-made</button><button data-route="cart" class="${state.route==='cart'?'active':''} cart-button"><b>◌</b>Cart<span class="cart-badge mobile">${cartCount()}</span></button></nav>`}
function home(){return shell(`<section class="hero"><div class="hero-copy"><span class="eyebrow">Custom T-shirt studio</span><h1>Create yours. Or choose ready-made.</h1><p>Design one T-shirt from scratch with your own colour, cloth, print, text and images — or shop ready-made products directly by category.</p><div class="hero-actions"><button class="primary-btn" data-route="customize">Create a T-shirt</button><button class="ghost-btn" data-route="catalog">Shop ready-made</button></div></div><div class="hero-art"><div class="hero-orbit"></div><div class="hero-tee"><span class="hero-color"></span><img src="assets/tshirt-front.webp" alt="Custom T-shirt" fetchpriority="high"></div></div></section>
<section class="section"><div class="section-head"><div><span class="eyebrow">Shop by category</span><h2>Choose what you need</h2><p>No search box, no clutter. Open a category and then narrow it using the filters.</p></div><button class="text-link" data-route="catalog">View all ready-made →</button></div>${categoryCards()}<div class="feature-strip"><div class="feature"><b>Custom T-shirt only</b><span>The designer is kept separate from ready-made items, so customers do not accidentally customize stock products.</span></div><div class="feature"><b>Exact colour preview</b><span>Front, back and sleeve views use the selected T-shirt colour while preserving realistic fabric shadows.</span></div><div class="feature"><b>Smart print compatibility</b><span>Light-only printing automatically disables when a dark colour is selected.</span></div></div></section>
<section class="section"><div class="section-head"><div><span class="eyebrow">Ready-made</span><h2>Popular products</h2><p>Simple product cards only. Categories and subcategories stay inside the category flow and filter panel.</p></div></div><div class="products-grid">${products.slice(0,4).map(productCard).join('')}</div></section>`)}
function categoryCards(){return `<div class="category-grid">${categories.map(c=>`<button class="category-card" data-category="${esc(c.name)}"><div class="category-photo"><img src="${c.image}" alt="${esc(c.name)}" loading="lazy"></div><div class="category-meta"><strong>${esc(c.name)}</strong><span>${c.sub.length} types available</span></div></button>`).join('')}</div>`}
function productCard(p){return `<article class="product-card"><button data-product="${p.id}"><div class="product-image"><img src="${p.image}" alt="${esc(p.name)}" loading="lazy"></div><div class="product-body"><div class="product-name">${esc(p.name)}</div><div class="product-note">${esc(p.desc)}</div><div class="price-row"><span class="price">${money(p.price)} <s>${money(p.mrp)}</s></span><span class="mini-add">View</span></div></div></button></article>`}
function catalog(){const filtered=getFiltered();return shell(`<div class="page-title"><span class="eyebrow">Ready-made collection</span><h1>Browse by category</h1><p>Use the category cards or filters. Search has been removed completely from the customer site.</p></div><div style="margin-bottom:24px">${categoryCards()}</div><div class="filter-mobile"><span>${filtered.length} products</span><button id="openFilters">Filters ${activeFilterCount()?`(${activeFilterCount()})`:''}</button></div><div class="catalog-layout">${filterPanel()}<section><div class="catalog-main-head"><span>${filtered.length} ready-made product${filtered.length===1?'':'s'}</span>${activeFilterCount()?'<button class="text-link" id="clearFiltersTop">Clear filters</button>':''}</div><div class="products-grid">${filtered.length?filtered.map(productCard).join(''):'<div class="empty">No items match those filters. Clear a filter and try again.</div>'}</div></section></div>`)}
function allSubs(){const cats=state.filters.categories.length?categories.filter(c=>state.filters.categories.includes(c.name)):categories;return [...new Set(cats.flatMap(c=>c.sub))]}
function allSizes(){return [...new Set(products.flatMap(p=>p.sizes))]}
function allOptions(){return [...new Set(products.flatMap(p=>p.options))]}
function checkGroup(title,key,items){return `<div class="filter-group"><h4>${title}</h4>${items.map(v=>`<label class="check-row"><input type="checkbox" data-filter="${key}" value="${esc(v)}" ${state.filters[key].includes(v)?'checked':''}><span>${esc(v)}</span></label>`).join('')}</div>`}
function filterPanel(){return `<aside class="filter-panel"><div class="filter-title"><strong>Filters</strong><button id="clearFilters">Clear all</button></div>${checkGroup('Categories','categories',categories.map(c=>c.name))}${checkGroup('Subcategories','subs',allSubs())}${checkGroup('Sizes','sizes',allSizes())}${checkGroup('Options','options',allOptions())}</aside>`}
function activeFilterCount(){return Object.values(state.filters).reduce((n,a)=>n+a.length,0)}
function getFiltered(){return products.filter(p=>(!state.filters.categories.length||state.filters.categories.includes(p.category))&&(!state.filters.subs.length||state.filters.subs.includes(p.subcategory))&&(!state.filters.sizes.length||state.filters.sizes.some(x=>p.sizes.includes(x)))&&(!state.filters.options.length||state.filters.options.some(x=>p.options.includes(x))))}
function customizer(){const c=state.custom, fab=fabrics.find(x=>x.id===c.fabric), pr=prints.find(x=>x.id===c.print), total=(fab.price+pr.price)*c.qty;return shell(`<div class="page-title"><span class="eyebrow">T-shirt customization</span><h1>Create your own T-shirt</h1><p>Only this section is customizable. Ready-made products stay ready-made.</p></div><div class="customizer-layout"><section class="studio"><div class="surface-tabs">${Object.entries(surfaces).map(([k,v])=>`<button class="surface-tab ${c.surface===k?'active':''}" data-surface="${k}">${v.label}</button>`).join('')}</div>${garmentPreview()}<div class="studio-hint"><span>Drag a selected text or image directly on the T-shirt.</span><span>${Object.values(c.layers).flat().length} layer${Object.values(c.layers).flat().length===1?'':'s'}</span></div></section><section class="custom-controls">${colorCard()}${materialCard()}${designCard()}${orderCard(total)}</section></div>`)}
function garmentPreview(){const c=state.custom,s=surfaces[c.surface],isSleeve=['left','right'].includes(c.surface),layers=c.layers[c.surface]||[];return `<div class="preview-wrap"><div class="garment ${isSleeve?'sleeve '+c.surface:c.surface}" style="--tee:${c.color};--garment-url:url('${s.asset}')"><span class="garment-color"></span><img class="garment-shade" src="${s.asset}" alt="${s.label}"><div class="print-zone" id="printZone">${layers.map(layerMarkup).join('')}</div></div></div>`}
function layerMarkup(l){if(l.type==='text')return `<div class="design-layer text ${state.custom.selected===l.id?'selected':''}" data-layer="${l.id}" style="--x:${l.x}%;--y:${l.y}%;--rot:${l.rot}deg;--size:${l.size}px;--color:${l.color};--font:${esc(l.font)}">${esc(l.text)}</div>`;return `<img class="design-layer image ${state.custom.selected===l.id?'selected':''}" data-layer="${l.id}" src="${l.src}" alt="Uploaded design" style="--x:${l.x}%;--y:${l.y}%;--rot:${l.rot}deg;--size:${l.size}px">`}
function colorCard(){const c=state.custom;return `<div class="control-card"><h3>1. T-shirt colour</h3><p class="help">Choose any colour. The same colour is applied to the front, back and both sleeve views.</p><div class="swatches">${colors.map(([n,h])=>`<button class="swatch ${c.color.toLowerCase()===h.toLowerCase()?'active':''}" aria-label="${n}" title="${n}" data-color="${h}" data-color-name="${n}" style="--sw:${h}"></button>`).join('')}<label class="custom-color"><input id="customColor" type="color" value="${c.color}"><span>Any colour</span></label></div></div>`}
function materialCard(){const c=state.custom;return `<div class="control-card"><h3>2. Cloth & printing</h3><div class="field"><label for="fabricSelect">Cloth type</label><select id="fabricSelect">${fabrics.map(f=>`<option value="${f.id}" ${c.fabric===f.id?'selected':''}>${f.name} · ${money(f.price)}</option>`).join('')}</select></div><div class="field"><label>Printing type</label><div class="print-grid">${prints.map(p=>`<button class="print-option ${c.print===p.id?'active':''}" data-print="${p.id}" ${p.lightOnly&&!isLight(c.color)?'disabled':''}><strong>${p.name} · +${money(p.price)}</strong><span>${p.note}</span></button>`).join('')}</div>${!isLight(c.color)?`<div class="notice"><b>Sublimation is disabled for this colour.</b><br>This printing is not visible properly on dark colours. Select a light T-shirt colour to use it.</div>`:''}</div></div>`}
function selectedLayer(){return Object.values(state.custom.layers).flat().find(l=>l.id===state.custom.selected)}
function designCard(){const sel=selectedLayer();return `<div class="control-card"><h3>3. Add your design</h3><div class="field"><label>Text</label><div class="tool-row"><input id="textInput" type="text" placeholder="Type text"><button class="soft-btn" id="addText">Add text</button></div></div><div class="tool-row"><label class="upload-btn">Add image<input id="imageInput" type="file" accept="image/*"></label><button class="ghost-btn" id="clearSurface">Clear this side</button></div>${sel?layerControls(sel):'<p class="help" style="margin-top:14px">Tap a design layer to edit its size, rotation and colour.</p>'}</div>`}
function layerControls(l){return `<div class="layer-controls"><div class="field"><label>Selected ${l.type==='text'?'text':'image'}</label>${l.type==='text'?`<input id="editText" type="text" value="${esc(l.text)}"><select id="fontSelect"><option ${l.font==='Arial'?'selected':''}>Arial</option><option ${l.font==='Impact'?'selected':''}>Impact</option><option ${l.font==='Georgia'?'selected':''}>Georgia</option><option ${l.font==='Courier New'?'selected':''}>Courier New</option></select><input id="textColor" type="color" value="${l.color}">`:''}</div><label class="range-row"><span>Size</span><input id="layerSize" type="range" min="${l.type==='text'?12:35}" max="${l.type==='text'?64:170}" value="${l.size}"><b>${l.size}</b></label><label class="range-row"><span>Rotate</span><input id="layerRotate" type="range" min="-180" max="180" value="${l.rot}"><b>${l.rot}°</b></label><button class="danger-btn" id="deleteLayer" style="width:100%;margin-top:6px">Delete selected layer</button></div>`}
function orderCard(total){const c=state.custom,f=fabrics.find(x=>x.id===c.fabric),p=prints.find(x=>x.id===c.print);return `<div class="control-card"><h3>4. Size & cart</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div class="field"><label>Size</label><select id="customSize">${['XS','S','M','L','XL','XXL','3XL'].map(x=>`<option ${c.size===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Quantity</label><input id="customQty" type="number" min="1" max="50" value="${c.qty}"></div></div><div class="custom-total"><span>${f.name}<br>${p.name}</span><strong>${money(total)}</strong></div><button class="primary-btn add-cart-wide" id="addCustomCart">Add customized T-shirt to cart</button></div>`}
function productModal(p){const selected={size:p.sizes[0],color:p.colors[0],option:p.options[0],qty:1};state.modal={type:'product',id:p.id,selected};return `<div class="modal-backdrop" id="modalBackdrop"><div class="modal"><button class="modal-close" id="closeModal">×</button><div class="product-modal"><div class="product-modal-image"><img src="${p.image}" alt="${esc(p.name)}"></div><div class="product-modal-info"><span class="eyebrow">${esc(p.category)}</span><h2>${esc(p.name)}</h2><div class="price" style="font-size:22px">${money(p.price)} <s>${money(p.mrp)}</s></div><p>${esc(p.desc)}</p><div class="field"><label>Size</label><div class="option-chips" data-choice="size">${p.sizes.map((x,i)=>`<button class="chip ${i===0?'active':''}" data-value="${esc(x)}">${esc(x)}</button>`).join('')}</div></div><div class="field"><label>Colour</label><div class="option-chips" data-choice="color">${p.colors.map((x,i)=>`<button class="chip ${i===0?'active':''}" data-value="${esc(x)}">${esc(x)}</button>`).join('')}</div></div><div class="field"><label>Option</label><div class="option-chips" data-choice="option">${p.options.map((x,i)=>`<button class="chip ${i===0?'active':''}" data-value="${esc(x)}">${esc(x)}</button>`).join('')}</div></div><div class="field"><label>Quantity</label><div class="qty"><button data-qty="-1">−</button><span id="modalQty">1</span><button data-qty="1">+</button></div></div><div class="modal-actions"><button class="primary-btn" id="addReadyCart">Add to cart · ${money(p.price)}</button></div></div></div></div></div>`}
function cart(){if(!state.cart.length)return shell(`<div class="page-title"><span class="eyebrow">Cart</span><h1>Your cart</h1></div><div class="success-card"><div class="success-icon" style="background:var(--brand-soft);color:var(--brand)">0</div><h2>Your cart is empty</h2><p style="color:var(--muted)">Create a custom T-shirt or choose a ready-made item.</p><div class="hero-actions" style="justify-content:center"><button class="primary-btn" data-route="customize">Customize</button><button class="ghost-btn" data-route="catalog">Ready-made</button></div></div>`);const subtotal=state.cart.reduce((n,x)=>n+x.price*x.qty,0);return shell(`<div class="page-title"><span class="eyebrow">Cart</span><h1>Your items</h1></div><div class="cart-layout"><div class="cart-list">${state.cart.map(cartItem).join('')}</div><aside class="summary"><h3>Order summary</h3><div class="summary-row"><span>Items</span><span>${cartCount()}</span></div><div class="summary-row"><span>Delivery</span><span>Calculated later</span></div><div class="summary-row total"><span>Total</span><span>${money(subtotal)}</span></div><div class="checkout-fields"><input id="custName" placeholder="Customer name"><input id="custPhone" inputmode="tel" placeholder="Phone number"><textarea id="custAddress" rows="3" placeholder="Delivery address"></textarea></div><button class="primary-btn" id="placeOrder">Place order</button></aside></div>`)}
function cartItem(x){return `<article class="cart-item"><div class="cart-thumb ${x.type==='custom'?'custom':''}" ${x.type==='custom'?`style="--c:${x.color}"`:''}>${x.type==='custom'?`<span class="cart-thumb-color"></span><img src="assets/tshirt-front.webp" alt="">`:`<img src="${x.image}" alt="${esc(x.name)}">`}</div><div class="cart-copy"><strong>${esc(x.name)}</strong><p>${x.type==='custom'?`${esc(x.fabricName)} · ${esc(x.printName)} · ${esc(x.size)} · ${esc(x.colorName)}`:`${esc(x.size)} · ${esc(x.color)} · ${esc(x.option)}`}<br>Qty: ${x.qty}</p><div class="price">${money(x.price*x.qty)}</div></div><button class="cart-remove" data-remove="${x.cartId}">Remove</button></article>`}
function orderSuccess(id){return shell(`<div class="success-card" style="margin-top:40px"><div class="success-icon">✓</div><h2>Order created</h2><p style="color:var(--muted)">Order <b>${id}</b> has been saved on this device.</p><button class="primary-btn" data-route="home">Back to home</button></div>`)}
function render(){let html=state.route==='home'?home():state.route==='catalog'?catalog():state.route==='customize'?customizer():state.route==='cart'?cart():home();$('#app').innerHTML=html;bind();renderBadges()}
function renderBadges(){$$('.cart-badge').forEach(x=>x.textContent=cartCount())}
function go(route){state.route=route;state.modal=null;state.drawer=false;$('#modalBackdrop')?.remove();$('#filterDrawer')?.remove();window.scrollTo({top:0,behavior:'instant'});render()}
function bind(){
 $$('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));
 $$('[data-category]').forEach(b=>b.onclick=()=>{state.filters={categories:[b.dataset.category],subs:[],sizes:[],options:[]};go('catalog')});
 $$('[data-product]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.product);document.body.insertAdjacentHTML('beforeend',productModal(p));bindModal(p)});
 $$('[data-filter]').forEach(i=>i.onchange=()=>{const k=i.dataset.filter,v=i.value,a=state.filters[k];state.filters[k]=i.checked?[...new Set([...a,v])]:a.filter(x=>x!==v);render()});
 const clear=()=>{state.filters={categories:[],subs:[],sizes:[],options:[]};render()};$('#clearFilters')&&($('#clearFilters').onclick=clear);$('#clearFiltersTop')&&($('#clearFiltersTop').onclick=clear);
 $('#openFilters')&&($('#openFilters').onclick=()=>{state.drawer=true;openFilterDrawerMarkup()});
 bindCustomizer();bindCart();
}
function openFilterDrawerMarkup(){if($('#filterDrawer'))return;document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop filter-drawer" id="filterDrawer"><div class="modal"><button class="modal-close" id="closeFilterDrawer">×</button>${filterPanel()}</div></div>`);$('#closeFilterDrawer').onclick=()=>{state.drawer=false;$('#filterDrawer').remove()};$('#filterDrawer').onclick=e=>{if(e.target.id==='filterDrawer'){state.drawer=false;e.currentTarget.remove()}};$$('#filterDrawer [data-filter]').forEach(i=>i.onchange=()=>{const k=i.dataset.filter,v=i.value,a=state.filters[k];state.filters[k]=i.checked?[...new Set([...a,v])]:a.filter(x=>x!==v);state.drawer=false;$('#filterDrawer').remove();render()});$('#filterDrawer #clearFilters').onclick=()=>{state.filters={categories:[],subs:[],sizes:[],options:[]};state.drawer=false;$('#filterDrawer').remove();render()}}
function bindCustomizer(){if(state.route!=='customize')return;const c=state.custom;
 $$('[data-surface]').forEach(b=>b.onclick=()=>{c.surface=b.dataset.surface;c.selected=null;render()});
 $$('[data-color]').forEach(b=>b.onclick=()=>setColor(b.dataset.color,b.dataset.colorName));$('#customColor')&&($('#customColor').oninput=e=>setColor(e.target.value,'Custom colour'));
 $('#fabricSelect').onchange=e=>{c.fabric=e.target.value;render()};$$('[data-print]').forEach(b=>b.onclick=()=>{c.print=b.dataset.print;render()});
 $('#addText').onclick=()=>{const v=$('#textInput').value.trim();if(!v)return toast('Type some text first');const l={id:'l'+Date.now(),type:'text',text:v,x:50,y:50,size:28,rot:0,color:'#151515',font:'Arial'};c.layers[c.surface].push(l);c.selected=l.id;render()};
 $('#imageInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const src=await imageData(f);const l={id:'l'+Date.now(),type:'image',src,x:50,y:50,size:90,rot:0};c.layers[c.surface].push(l);c.selected=l.id;render()}catch{toast('Could not use that image')}};
 $('#clearSurface').onclick=()=>{c.layers[c.surface]=[];c.selected=null;render()};
 $$('.design-layer').forEach(el=>{el.onclick=e=>{e.stopPropagation();c.selected=el.dataset.layer;render()};el.onpointerdown=e=>startDrag(e,el.dataset.layer)});$('#printZone')&&($('#printZone').onclick=()=>{if(c.selected){c.selected=null;render()}});
 const sel=selectedLayer();if(sel){$('#editText')&&($('#editText').oninput=e=>{sel.text=e.target.value;$('.design-layer.selected').textContent=sel.text});$('#fontSelect')&&($('#fontSelect').onchange=e=>{sel.font=e.target.value;$('.design-layer.selected').style.setProperty('--font',sel.font)});$('#textColor')&&($('#textColor').oninput=e=>{sel.color=e.target.value;$('.design-layer.selected').style.setProperty('--color',sel.color)});$('#layerSize').oninput=e=>{sel.size=Number(e.target.value);e.target.nextElementSibling.textContent=sel.size;$('.design-layer.selected').style.setProperty('--size',sel.size+'px')};$('#layerRotate').oninput=e=>{sel.rot=Number(e.target.value);e.target.nextElementSibling.textContent=sel.rot+'°';$('.design-layer.selected').style.setProperty('--rot',sel.rot+'deg')};$('#deleteLayer').onclick=()=>{c.layers[c.surface]=c.layers[c.surface].filter(x=>x.id!==sel.id);c.selected=null;render()}}
 $('#customSize').onchange=e=>c.size=e.target.value;$('#customQty').onchange=e=>{c.qty=Math.max(1,Math.min(50,Number(e.target.value)||1));render()};$('#addCustomCart').onclick=addCustomCart;
}
function setColor(hex,name){const c=state.custom;c.color=hex;c.colorName=name;if(!isLight(hex)&&prints.find(x=>x.id===c.print)?.lightOnly)c.print='dtf';render()}
function startDrag(e,id){e.preventDefault();const c=state.custom,layer=c.layers[c.surface].find(x=>x.id===id),zone=$('#printZone');if(!layer||!zone)return;c.selected=id;const move=ev=>{const r=zone.getBoundingClientRect();layer.x=Math.max(2,Math.min(98,(ev.clientX-r.left)/r.width*100));layer.y=Math.max(2,Math.min(98,(ev.clientY-r.top)/r.height*100));const el=$(`[data-layer="${id}"]`);if(el){el.style.setProperty('--x',layer.x+'%');el.style.setProperty('--y',layer.y+'%')}};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function imageData(file){return new Promise((res,rej)=>{const rd=new FileReader();rd.onerror=rej;rd.onload=()=>{const im=new Image();im.onerror=rej;im.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(im.width,im.height)),cv=document.createElement('canvas');cv.width=Math.round(im.width*scale);cv.height=Math.round(im.height*scale);cv.getContext('2d').drawImage(im,0,0,cv.width,cv.height);res(cv.toDataURL('image/webp',.84))};im.src=rd.result};rd.readAsDataURL(file)})}
function addCustomCart(){const c=state.custom,f=fabrics.find(x=>x.id===c.fabric),p=prints.find(x=>x.id===c.print);state.cart.push({cartId:'c'+Date.now(),type:'custom',name:'Custom T-shirt',price:f.price+p.price,qty:c.qty,size:c.size,color:c.color,colorName:c.colorName,fabric:c.fabric,fabricName:f.name,print:c.print,printName:p.name,layers:JSON.parse(JSON.stringify(c.layers))});saveCart();toast('Customized T-shirt added to cart')}
function bindModal(p){const root=$('#modalBackdrop');if(!root)return;$('#closeModal').onclick=()=>{state.modal=null;root.remove()};root.onclick=e=>{if(e.target===root){state.modal=null;root.remove()}};$$('[data-choice]',root).forEach(group=>$$('.chip',group).forEach(ch=>ch.onclick=()=>{const key=group.dataset.choice;state.modal.selected[key]=ch.dataset.value;$$('.chip',group).forEach(x=>x.classList.toggle('active',x===ch))}));$$('[data-qty]',root).forEach(b=>b.onclick=()=>{const s=state.modal.selected;s.qty=Math.max(1,Math.min(20,s.qty+Number(b.dataset.qty)));$('#modalQty').textContent=s.qty;$('#addReadyCart').textContent='Add to cart · '+money(p.price*s.qty)});$('#addReadyCart').onclick=()=>{const s=state.modal.selected;state.cart.push({cartId:'r'+Date.now(),type:'ready',productId:p.id,name:p.name,image:p.image,price:p.price,qty:s.qty,size:s.size,color:s.color,option:s.option});saveCart();state.modal=null;root.remove();toast('Added to cart')}}
function bindCart(){if(state.route!=='cart')return;$$('[data-remove]').forEach(b=>b.onclick=()=>{state.cart=state.cart.filter(x=>x.cartId!==b.dataset.remove);saveCart();render()});$('#placeOrder')&&($('#placeOrder').onclick=()=>{const name=$('#custName').value.trim(),phone=$('#custPhone').value.trim(),address=$('#custAddress').value.trim();if(!name||!phone||!address)return toast('Fill name, phone and address');const id='OL'+String(Date.now()).slice(-7);localStorage.setItem('oneline-last-order',JSON.stringify({id,name,phone,address,items:state.cart,createdAt:new Date().toISOString()}));state.cart=[];saveCart();$('#app').innerHTML=orderSuccess(id);bind()})}
render();
})();
