(()=>{
  'use strict';
  const S=window.OneLine,root=document.getElementById('app');
  const isB2B=document.body.dataset.mode==='b2b';
  const WA_LOGO='https://upload.wikimedia.org/wikipedia/commons/4/4c/WhatsApp_Logo_green.svg';
  const state={view:'home',params:{},query:'',filterCategory:'',filterSize:'',filterOpen:false,menu:false,customizer:null,productSelection:{}};
  const icons={
    menu:'<path d="M4 7h16M4 12h16M4 17h16"/>',bag:'<path d="M6 8h12l-1 12H7L6 8Z"/><path d="M9 8a3 3 0 0 1 6 0"/>',home:'<path d="m3 11 9-8 9 8"/><path d="M5 10v11h14V10M9 21v-7h6v7"/>',catalog:'<path d="M4 6h16M7 12h10M10 18h4"/>',plus:'<path d="M12 5v14M5 12h14"/>',orders:'<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4V2h6v2M9 9h6M9 13h6"/>',back:'<path d="m15 18-6-6 6-6M9 12h11"/>',share:'<circle cx="18" cy="5" r="2"/><circle cx="6" cy="12" r="2"/><circle cx="18" cy="19" r="2"/><path d="m8 11 8-5M8 13l8 5"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',filter:'<path d="M4 6h16M7 12h10M10 18h4"/>',arrow:'<path d="M5 12h14M14 6l6 6-6 6"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',minus:'<path d="M5 12h14"/>',trash:'<path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14"/>',zoom:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5M10.5 7.5v6M7.5 10.5h6"/>'
  };
  const I=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[n]||''}</svg>`;
  const toast=(msg)=>{let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1900)};
  const cartCount=()=>S.getCart().reduce((n,x)=>n+Number(x.qty||1),0);
  const discount=p=>p.mrp>p.price?Math.round((1-p.price/p.mrp)*100):0;
  const waButton=(text,msg)=>`<a class="btn wa-btn" href="${S.whatsappUrl(msg)}" target="_blank" rel="noopener"><img src="${WA_LOGO}" onerror="this.onerror=null;this.src='assets/whatsapp-logo-green.svg'" alt="WhatsApp">${S.esc(text)}</a>`;
  function header(active){return `<header class="site-header"><div class="header-inner">
    <button class="icon-btn mobile-menu-btn" data-menu aria-label="Menu">${I('menu')}</button>
    <a class="brand" href="#" data-nav="home"><img src="one-line-logo.webp" alt="One-Line"><span>One-Line</span></a>
    <nav class="header-nav"><button class="${active==='home'?'active':''}" data-nav="home">Home</button><button class="${active==='catalog'?'active':''}" data-nav="catalog">Ready-made</button><button class="${active==='customize'?'active':''}" data-nav="customize">Customize</button><a href="b2b.html">B2B</a></nav>
    <div class="header-actions"><button class="icon-btn desktop-only" data-nav="orders" aria-label="Orders">${I('orders')}</button><button class="icon-btn" data-nav="cart" aria-label="Cart">${I('bag')}<span class="cart-count">${cartCount()}</span></button></div>
  </div></header>`;}
  function bottomNav(active){return `<nav class="bottom-nav">
    <button class="${active==='home'?'active':''}" data-nav="home">${I('home')}<span>Home</span></button>
    <button class="${active==='catalog'?'active':''}" data-nav="catalog">${I('catalog')}<span>Catalog</span></button>
    <button class="create-nav ${active==='customize'?'active':''}" data-nav="customize">${I('plus')}<span>Create</span></button>
    <button data-b2b>${I('catalog')}<span>B2B</span></button>
    <button class="${active==='cart'?'active':''}" data-nav="cart">${I('bag')}<span>Cart</span></button>
  </nav>`;}
  function mobileMenu(){return state.menu?`<div class="drawer-backdrop" data-close-menu><div class="drawer" style="width:min(330px,88vw);margin-right:auto" onclick="event.stopPropagation()"><div class="drawer-head"><strong>Menu</strong><button class="icon-btn" data-close-menu>${I('close')}</button></div><div style="display:grid;gap:8px;margin-top:22px"><button class="btn btn-ghost" data-nav="home">Home</button><button class="btn btn-ghost" data-nav="catalog">Ready-made</button><button class="btn btn-ghost" data-nav="customize">Customize</button><button class="btn btn-ghost" data-nav="orders">My orders</button><a class="btn btn-ghost" href="b2b.html">B2B catalogue</a></div></div></div>`:'';}
  function shell(content,active=''){root.innerHTML=header(active)+`<main class="main">${content}</main>`+bottomNav(active)+mobileMenu();}
  function productCard(p){return `<article class="product-card">
    <div class="product-media" data-product="${p.id}"><img src="${S.esc(p.image)}" alt="${S.esc(p.name)}" loading="lazy">${discount(p)?`<span class="discount">-${discount(p)}%</span>`:''}<button class="share-mini" data-share="${p.id}" aria-label="Share">${I('share')}</button></div>
    <div class="product-body"><div class="product-kicker">${S.esc(p.subcategory)}</div><div class="product-name" data-product="${p.id}">${S.esc(p.name)}</div><div class="price-row"><span class="price">${S.money(p.price)}</span>${p.mrp>p.price?`<span class="mrp">${S.money(p.mrp)}</span>`:''}</div><div class="card-actions"><button class="btn btn-primary" data-add="${p.id}">Add to cart</button><button class="quick-view" data-product="${p.id}" aria-label="View product">${I('arrow')}</button></div></div>
  </article>`;}
  function renderHome(){
    const categories=S.getCategories().filter(c=>c.active!==false).sort((a,b)=>(a.order||0)-(b.order||0));
    const products=S.getProducts().filter(p=>p.audience==='retail'&&p.active!==false).slice(0,4);
    const content=`<section class="hero"><div class="page"><div class="hero-card"><div class="hero-copy"><p class="eyebrow">Custom apparel studio</p><h1>Made for your team.</h1><p>Design your own T-shirt, polo or sportswear, or order ready-made clothing directly from the catalogue.</p><div class="hero-actions"><button class="btn btn-primary" data-nav="customize">Start customizing ${I('arrow')}</button><button class="btn btn-secondary" data-nav="catalog">Shop ready-made</button></div></div><div class="hero-visual"><span class="hero-badge">Print · Embroidery · Teamwear</span><img class="hero-shirt" src="assets/uniform-shirt-front.webp" alt="Custom apparel"></div></div></div></section>
      <section class="section"><div class="page"><div class="section-head"><div><p class="eyebrow">Browse by category</p><h2>Ready-made collections</h2><p>Large, image-first category cards with no wasted box space.</p></div><button class="text-link" data-nav="catalog">View all products →</button></div><div class="category-grid">${categories.map(c=>`<button class="category-card" data-category="${S.esc(c.name)}"><img class="category-image" src="${S.esc(c.image)}" alt="${S.esc(c.name)}"><span class="category-overlay"><span class="category-name">${S.esc(c.name)}</span><span class="category-sub">${S.esc(c.subtitle||'')}</span></span></button>`).join('')}</div></div></section>
      <section class="section"><div class="page"><div class="section-head"><div><p class="eyebrow">Ready to order</p><h2>Popular ready-made</h2></div></div><div class="product-grid">${products.map(productCard).join('')}</div><div class="view-all-wrap"><button class="view-all-btn" data-nav="catalog">View all products ${I('arrow')}</button></div></div></section>
      <section class="section"><div class="page"><div class="uniform-cta"><div class="uniform-copy"><p class="eyebrow">Custom uniform orders</p><h2>Need uniforms for a full team?</h2><p>Send your quantity, logo and garment requirement. We can discuss sizing, print method and production details directly.</p>${waButton('Enquire to customise','Hello, I need a custom uniform order. Please share the options.')}</div><div class="uniform-image"><img src="assets/category-uniforms.webp" alt="Custom uniform order"></div></div></div></section>
      <section class="section"><div class="page"><div class="feature-row"><div class="feature-card"><strong>Simple customization</strong><span>Add text or artwork, move it directly on the garment, resize and rotate it.</span></div><div class="feature-card"><strong>Ready-made ordering</strong><span>Add standard products to cart without entering the customizer.</span></div><div class="feature-card"><strong>B2B enquiries</strong><span>Wholesale items stay separate from retail products and use direct price enquiry.</span></div></div></div></section>`;
    shell(content,'home');
  }
  function filteredProducts(){let list=S.searchProducts(state.query,'retail');if(state.filterCategory)list=list.filter(p=>p.category===state.filterCategory);if(state.filterSize)list=list.filter(p=>(S.optionsFor(p,p.colors?.[0])||p.sizes||[]).includes(state.filterSize)||(p.sizes||[]).includes(state.filterSize));return list;}
  function filterDrawer(){if(!state.filterOpen)return'';const cats=S.getCategories().filter(c=>c.active!==false);const sizes=['S','M','L','XL','XXL','38','40','42','44'];return `<div class="drawer-backdrop" data-filter-close><aside class="drawer" onclick="event.stopPropagation()"><div class="drawer-head"><h3>Filter</h3><button class="icon-btn" data-filter-close>${I('close')}</button></div><div class="filter-section"><label>Category</label><div class="chip-row"><button class="chip ${!state.filterCategory?'selected':''}" data-filter-category="">All</button>${cats.map(c=>`<button class="chip ${state.filterCategory===c.name?'selected':''}" data-filter-category="${S.esc(c.name)}">${S.esc(c.name)}</button>`).join('')}</div></div><div class="filter-section"><label>Size</label><div class="chip-row"><button class="chip ${!state.filterSize?'selected':''}" data-filter-size="">Any</button>${sizes.map(s=>`<button class="chip ${state.filterSize===s?'selected':''}" data-filter-size="${s}">${s}</button>`).join('')}</div></div><button class="btn btn-primary btn-wide" style="margin-top:20px" data-filter-close>Show products</button></aside></div>`;}
  function renderCatalog(){const list=filteredProducts();const cats=[...new Set(list.map(p=>p.category))];const content=`<section class="catalog-hero"><div class="page"><div class="catalog-title-row"><div class="catalog-title"><p class="eyebrow">Ready-made</p><h1>Catalog</h1><p>Tap a product to view colour, size and product details.</p></div><div class="catalog-tools"><button class="filter-btn" data-filter-open>${I('filter')} Filter</button></div></div><div class="search-wrap"><input class="search-box" id="catalog-search" value="${S.esc(state.query)}" placeholder="Search products, categories or keywords"><button class="filter-btn" data-filter-open>${I('filter')}</button></div>${state.filterCategory||state.filterSize?`<span class="active-filter">${S.esc([state.filterCategory,state.filterSize].filter(Boolean).join(' · '))}</span>`:''}</div></section><section class="section" style="padding-top:0"><div class="page">${list.length?cats.map(cat=>`<div class="catalog-group"><div class="catalog-group-head"><h2>${S.esc(cat)}</h2><small>${list.filter(p=>p.category===cat).length} items</small></div><div class="product-grid">${list.filter(p=>p.category===cat).map(productCard).join('')}</div></div>`).join(''):`<div class="empty">No matching products found. Try another search or clear the filter.</div>`}</div></section>${filterDrawer()}`;shell(content,'catalog');q('#catalog-search')?.addEventListener('input',e=>{state.query=e.target.value;clearTimeout(state.searchTimer);state.searchTimer=setTimeout(renderCatalog,160);});}
  function productSelection(p){if(!state.productSelection[p.id])state.productSelection[p.id]={color:p.colors?.[0]||'',size:(p.sizes||[])[0]||'',image:0};return state.productSelection[p.id];}
  function renderProduct(id){const p=S.productById(id);if(!p){navigate('catalog');return}const sel=productSelection(p),image=S.imageFor(p,sel.color)||p.images?.[sel.image]||p.image;const options=S.optionsFor(p,sel.color);if(options.length&&!options.includes(sel.size))sel.size=options[0];const thumbs=[...new Set([image,...(p.images||[])])];const content=`<section class="product-page"><div class="page"><div class="back-row"><button class="back-btn" data-back>${I('back')}</button></div><div class="product-layout"><div class="product-gallery"><div class="thumbs">${thumbs.map((src,i)=>`<button class="thumb ${src===image?'active':''}" data-product-image="${S.esc(src)}"><img src="${S.esc(src)}" alt=""></button>`).join('')}</div><div class="main-product-image" id="product-zoom"><img id="product-main-image" src="${S.esc(image)}" alt="${S.esc(p.name)}"><span class="zoom-hint">${I('zoom')} Tap or pinch to zoom</span></div></div><div class="product-info"><div class="product-kicker">${S.esc(p.category)} · ${S.esc(p.subcategory)}</div><h1>${S.esc(p.name)}</h1><div class="price-row"><span class="price">${S.money(p.price)}</span>${p.mrp>p.price?`<span class="mrp">${S.money(p.mrp)}</span>`:''}</div><p class="desc">${S.esc(p.description||'')}</p>${p.colors?.length?`<div class="selector-block"><div class="selector-label">Colour · ${S.esc(sel.color)}</div><div class="swatches">${p.colors.map(c=>`<button class="swatch ${sel.color===c?'selected':''}" data-select-color="${S.esc(c)}" style="background:${S.palette[c]||c}" title="${S.esc(c)}"></button>`).join('')}</div></div>`:''}${options.length?`<div class="selector-block"><div class="selector-label">${S.esc(p.optionTitle||'Option')}</div><div class="options">${options.map(o=>`<button class="option ${sel.size===o?'selected':''}" data-select-size="${S.esc(o)}">${S.esc(o)}</button>`).join('')}</div></div>`:''}<div class="product-cta"><button class="btn btn-primary" data-add-current="${p.id}">Add to cart</button><button class="icon-btn" data-share="${p.id}" aria-label="Share">${I('share')}</button></div><div class="custom-enquiry"><div style="display:flex;align-items:center;gap:10px"><img src="${WA_LOGO}" onerror="this.onerror=null;this.src='assets/whatsapp-logo-green.svg'" alt="WhatsApp"><div><strong>Need this customised?</strong><span>Discuss logo, print or bulk requirements.</span></div></div><button data-wa-product="${p.id}">Enquire</button></div></div></div></div></section>`;shell(content,'catalog');bindProductZoom();}
  function bindProductZoom(){const box=q('#product-zoom'),img=q('#product-main-image');if(!box||!img)return;let scale=1,startDist=0,startScale=1,moved=false;box.addEventListener('click',()=>{if(moved){moved=false;return}scale=scale>1?1:1.75;box.classList.toggle('zoomed',scale>1);img.style.transform=scale===1?'':'scale('+scale+')';});box.addEventListener('touchstart',e=>{if(e.touches.length===2){startDist=Math.hypot(e.touches[1].clientX-e.touches[0].clientX,e.touches[1].clientY-e.touches[0].clientY);startScale=scale;moved=true;}},{passive:true});box.addEventListener('touchmove',e=>{if(e.touches.length!==2)return;e.preventDefault();const d=Math.hypot(e.touches[1].clientX-e.touches[0].clientX,e.touches[1].clientY-e.touches[0].clientY);scale=Math.max(1,Math.min(3,startScale*(d/(startDist||d))));img.style.transform=`scale(${scale})`;box.classList.toggle('zoomed',scale>1.02);},{passive:false});}
  function renderCart(){const cart=S.getCart();const content=`<section class="cart-page"><div class="page"><h1 class="page-title">Your cart</h1>${cart.length?`<div class="cart-layout"><div class="cart-list">${cart.map(x=>`<article class="cart-item"><img class="cart-image" src="${S.esc(x.image)}" alt="${S.esc(x.name)}"><div><div class="product-kicker">${x.custom?'Custom design':'Ready-made'}</div><h3>${S.esc(x.name)}</h3><div class="cart-meta">${S.esc([x.color,x.size,x.print].filter(Boolean).join(' · '))}</div><div class="qty"><button data-qty="${x.cartKey}" data-delta="-1">${I('minus')}</button><span>${x.qty}</span><button data-qty="${x.cartKey}" data-delta="1">${I('plus')}</button></div><br><button class="remove-link" data-remove="${x.cartKey}">Remove</button></div><div style="font-weight:850;text-align:right">${S.money(Number(x.price)*Number(x.qty))}</div></article>`).join('')}</div><aside class="cart-side"><div class="summary-row"><span>Items</span><strong>${cartCount()}</strong></div><div class="summary-row total"><span>Total</span><span>${S.money(S.cartTotal())}</span></div><button class="btn btn-primary btn-wide" style="margin-top:16px" data-nav="checkout">Continue to checkout</button><button class="btn btn-secondary btn-wide" style="margin-top:8px" data-nav="catalog">Continue shopping</button></aside></div>`:`<div class="empty"><p>Your cart is empty.</p><button class="btn btn-primary" data-nav="catalog">Browse products</button></div>`}</div></section>`;shell(content,'cart');}
  function renderCheckout(){if(!S.getCart().length){navigate('cart');return}const delivery=S.getDelivery().filter(x=>x.active!==false);const content=`<section class="checkout-page"><div class="page"><h1 class="page-title" style="text-align:center">Checkout</h1><form class="checkout-card" id="checkout-form"><div class="form-grid"><div class="field"><label>Name</label><input name="name" required autocomplete="name"></div><div class="field"><label>Phone</label><input name="phone" required inputmode="tel" autocomplete="tel"></div><div class="field full"><label>Address</label><textarea name="address" required autocomplete="street-address"></textarea></div><div class="field full"><label>Delivery</label><div class="choice-list">${delivery.map((d,i)=>`<label class="choice"><input type="radio" name="delivery" value="${S.esc(d.name)}" ${i===0?'checked':''}><span><strong>${S.esc(d.name)}</strong><br><small>${S.esc(d.note)}</small></span></label>`).join('')}</div></div><div class="field full"><label>Payment</label><div class="choice"><input type="radio" checked><span><strong>Confirm order</strong><br><small>Payment arrangements can be connected later.</small></span></div></div></div><div class="summary-row total" style="margin-top:20px"><span>Total</span><span>${S.money(S.cartTotal())}</span></div><button class="btn btn-primary btn-wide" style="margin-top:16px" type="submit">Place order</button></form></div></section>`;shell(content,'cart');q('#checkout-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const order=S.createOrder({name:f.get('name'),phone:f.get('phone'),address:f.get('address'),delivery:f.get('delivery')});toast(`Order ${order.id} confirmed`);navigate('orders');});}
  function renderOrders(){const orders=S.getOrders();const content=`<section class="orders-page"><div class="page"><h1 class="page-title">Orders</h1>${orders.length?orders.map(o=>`<article class="order-card"><div class="order-head"><div><strong>${S.esc(o.id)}</strong><div class="cart-meta">${new Date(o.createdAt).toLocaleString()}</div></div><span class="status">${S.esc(o.status)}</span></div><div class="order-items">${o.items.map(i=>`${S.esc(i.name)} × ${i.qty}`).join(' · ')}</div><div class="summary-row total"><span>Total</span><span>${S.money(o.total)}</span></div></article>`).join(''):`<div class="empty">No orders yet.</div>`}</div></section>`;shell(content,'orders');}
  function renderCustomizer(){root.innerHTML='<main class="main"><div id="customizer-root"></div></main>'+bottomNav('customize');state.customizer?.destroy?.();state.customizer=window.OneLineCustomizer.mount(q('#customizer-root'),{onBack:()=>history.back(),onAdd:()=>{toast('Custom item added to cart');navigate('cart')}});}
  function render(){state.customizer?.destroy?.();state.customizer=null;if(state.view==='home')renderHome();else if(state.view==='catalog')renderCatalog();else if(state.view==='product')renderProduct(state.params.id);else if(state.view==='cart')renderCart();else if(state.view==='checkout')renderCheckout();else if(state.view==='orders')renderOrders();else if(state.view==='customize')renderCustomizer();else renderHome();}
  function navigate(view,params={},push=true){state.view=view;state.params=params;state.menu=false;state.filterOpen=false;if(push)history.pushState({view,params},'',view==='home'?location.pathname:`#${view}${params.id?'/'+params.id:''}`);render();requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'auto'}));}
  const q=s=>document.querySelector(s);
  function defaultCartItem(p){const color=p.colors?.[0]||'',size=S.optionsFor(p,color)[0]||p.sizes?.[0]||'';return{cartKey:S.uid('CART'),productId:p.id,name:p.name,price:p.price,image:S.imageFor(p,color)||p.image,qty:1,color,size,custom:false};}
  function addProduct(p,sel){if(!p)return;S.addCart({cartKey:S.uid('CART'),productId:p.id,name:p.name,price:p.price,image:S.imageFor(p,sel?.color)||p.image,qty:1,color:sel?.color||p.colors?.[0]||'',size:sel?.size||S.optionsFor(p,sel?.color||p.colors?.[0]||'')[0]||p.sizes?.[0]||'',custom:false});toast('Added to cart');renderHeaderCount();}
  function renderHeaderCount(){document.querySelectorAll('.cart-count').forEach(x=>x.textContent=cartCount());}
  async function shareProduct(id){const p=S.productById(id);if(!p)return;const data={title:p.name,text:`${p.name} — ${S.money(p.price)}`,url:location.origin+location.pathname+'#product/'+p.id};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);toast('Product link copied')}}catch{}}
  function openWAProduct(id){const p=S.productById(id);if(!p)return;window.open(S.whatsappUrl(`Hello, I want to customise ${p.name}. Please share the options.`),'_blank','noopener');}
  root.addEventListener('click',e=>{
    const nav=e.target.closest('[data-nav]');if(nav){e.preventDefault();navigate(nav.dataset.nav);return}
    if(e.target.closest('[data-menu]')){state.menu=true;render();return}
    if(e.target.closest('[data-close-menu]')){state.menu=false;render();return}
    if(e.target.closest('[data-b2b]')){location.href='b2b.html';return}
    const cat=e.target.closest('[data-category]');if(cat){state.filterCategory=cat.dataset.category;state.query='';navigate('catalog');return}
    const sh=e.target.closest('[data-share]');if(sh){e.preventDefault();e.stopPropagation();shareProduct(sh.dataset.share);return}
    const add=e.target.closest('[data-add]');if(add){e.stopPropagation();addProduct(S.productById(add.dataset.add));return}
    const addCur=e.target.closest('[data-add-current]');if(addCur){addProduct(S.productById(addCur.dataset.addCurrent),productSelection(S.productById(addCur.dataset.addCurrent)));return}
    const prod=e.target.closest('[data-product]');if(prod){navigate('product',{id:prod.dataset.product});return}
    if(e.target.closest('[data-filter-open]')){state.filterOpen=true;renderCatalog();return}
    if(e.target.closest('[data-filter-close]')){state.filterOpen=false;renderCatalog();return}
    const fc=e.target.closest('[data-filter-category]');if(fc){state.filterCategory=fc.dataset.filterCategory;renderCatalog();return}
    const fs=e.target.closest('[data-filter-size]');if(fs){state.filterSize=fs.dataset.filterSize;renderCatalog();return}
    const back=e.target.closest('[data-back]');if(back){history.back();return}
    const color=e.target.closest('[data-select-color]');if(color){const p=S.productById(state.params.id),sel=productSelection(p);sel.color=color.dataset.selectColor;sel.size=S.optionsFor(p,sel.color)[0]||'';renderProduct(p.id);return}
    const size=e.target.closest('[data-select-size]');if(size){const p=S.productById(state.params.id);productSelection(p).size=size.dataset.selectSize;renderProduct(p.id);return}
    const img=e.target.closest('[data-product-image]');if(img){const main=q('#product-main-image');if(main)main.src=img.dataset.productImage;document.querySelectorAll('.thumb').forEach(t=>t.classList.toggle('active',t===img));return}
    const wa=e.target.closest('[data-wa-product]');if(wa){openWAProduct(wa.dataset.waProduct);return}
    const qty=e.target.closest('[data-qty]');if(qty){const item=S.getCart().find(x=>x.cartKey===qty.dataset.qty);if(item){const n=Math.max(1,Number(item.qty)+Number(qty.dataset.delta));S.updateCart(item.cartKey,{qty:n});renderCart()}return}
    const rem=e.target.closest('[data-remove]');if(rem){S.removeCart(rem.dataset.remove);renderCart();return}
  });
  window.addEventListener('popstate',e=>{const s=e.state;if(s?.view){state.view=s.view;state.params=s.params||{};}else{state.view='home';state.params={};}render();requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'auto'}));});
  window.addEventListener('one-line-data',e=>{if(e.detail?.key===S.KEYS.cart)renderHeaderCount();});

  function renderB2B(){
    const logged=sessionStorage.getItem('one-line-b2b')==='1';
    if(!logged){
      root.innerHTML=`<section class="b2b-login"><form class="login-card" id="b2b-login"><img src="one-line-logo.webp" alt=""><p class="eyebrow">Wholesale access</p><h1>B2B catalogue</h1><p>Sign in with the B2B credentials configured by the store admin.</p><div class="control-grid"><div class="field"><label>B2B ID</label><input name="id" required></div><div class="field"><label>Password</label><input name="password" type="password" required></div><button class="btn btn-primary btn-wide" type="submit">Open catalogue</button><a class="btn btn-secondary btn-wide" href="index.html">Back to retail site</a></div></form></section>`;
      q('#b2b-login').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),set=S.getSettings();if(f.get('id')===set.b2bId&&f.get('password')===set.b2bPassword){sessionStorage.setItem('one-line-b2b','1');renderB2B()}else toast('Incorrect B2B credentials')});
      return;
    }
    const products=S.getProducts().filter(p=>p.audience==='b2b'&&p.active!==false);
    root.innerHTML=`<header class="site-header"><div class="header-inner"><a class="brand" href="index.html"><img src="one-line-logo.webp" alt="One-Line"><span>One-Line B2B</span></a><div></div><div class="header-actions"><a class="btn btn-secondary" href="index.html">Retail store</a><button class="btn btn-ghost" id="b2b-logout">Sign out</button></div></div></header><main class="main"><section class="catalog-hero"><div class="page"><div class="catalog-title"><p class="eyebrow">Wholesale</p><h1>B2B catalogue</h1><p>Prices are supplied by enquiry based on quantity and current material rate.</p></div></div></section><section class="section" style="padding-top:0"><div class="page"><div class="product-grid">${products.map(p=>`<article class="product-card"><div class="product-media"><img src="${S.esc(p.image)}" alt="${S.esc(p.name)}"></div><div class="product-body"><div class="product-kicker">${S.esc(p.subcategory)}</div><div class="product-name">${S.esc(p.name)}</div><p style="font-size:13px;color:var(--muted);min-height:42px">${S.esc(p.description)}</p><a class="btn wa-btn btn-wide" href="${S.whatsappUrl(`Hello, please share the B2B price for ${p.name}.`)}" target="_blank" rel="noopener"><img src="${WA_LOGO}" onerror="this.onerror=null;this.src='assets/whatsapp-logo-green.svg'" alt="WhatsApp">Ask for price</a></div></article>`).join('')}</div></div></section></main>`;
    q('#b2b-logout')?.addEventListener('click',()=>{sessionStorage.removeItem('one-line-b2b');renderB2B();});
  }
  if(isB2B){renderB2B();return}
  history.replaceState({view:'home',params:{}},'',location.pathname);render();
})();
