(()=>{
  'use strict';
  const S=window.OneLine,root=document.getElementById('portal'),role=document.body.dataset.portalRole||'admin';
  const state={view:role==='receiver'?'orders':'dashboard',modal:null,editing:null};
  const icons={dash:'<path d="M4 4h6v6H4zM14 4h6v10h-6zM4 14h6v6H4zM14 18h6v2h-6z"/>',box:'<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M4 9h16"/>',cat:'<path d="M4 5h7v7H4zM13 5h7v7h-7zM4 14h7v5H4zM13 14h7v5h-7z"/>',orders:'<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4V2h6v2M9 9h6M9 13h6"/>',stock:'<path d="m4 7 8-4 8 4-8 4-8-4Z"/><path d="M4 7v10l8 4 8-4V7M12 11v10"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1a7 7 0 0 0-1.7-1L14.5 3h-5l-.4 3.1a7 7 0 0 0-1.7 1l-2.4-1-2 3.4L5.1 11a7 7 0 0 0 0 2L3 14.5l2 3.4 2.4-1a7 7 0 0 0 1.7 1l.4 3.1h5l.4-3.1a7 7 0 0 0 1.7-1l2.4 1 2-3.4-2.1-1.5a7 7 0 0 0 .1-1Z"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M4 19c.6-3 2.2-4.5 5-4.5s4.4 1.5 5 4.5M16 7h4M18 5v4"/>',custom:'<path d="M12 3v18M3 12h18"/>',logout:'<path d="M10 4H5v16h5M14 8l4 4-4 4M18 12H9"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',edit:'<path d="m4 20 4-.8L19 8.2 15.8 5 4.8 16 4 20Z"/>',trash:'<path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14"/>',plus:'<path d="M12 5v14M5 12h14"/>'};
  const I=n=>`<svg class="icon" viewBox="0 0 24 24">${icons[n]||''}</svg>`;
  const allowed={
    admin:[['dashboard','Overview','dash'],['products','Products','box'],['categories','Categories','cat'],['customization','Customization','custom'],['orders','Orders','orders'],['accounts','Accounts','users'],['settings','Settings','settings']],
    management:[['dashboard','Overview','dash'],['products','Products','box'],['categories','Categories','cat'],['orders','Orders','orders']],
    staff:[['dashboard','Overview','dash'],['stock','Stock','stock'],['products','Manage','box']],
    receiver:[['orders','Orders','orders']]
  }[role]||[];
  const sessionKey=`one-line-session-${role}`;
  const logged=()=>sessionStorage.getItem(sessionKey)==='1';
  const title=()=>allowed.find(x=>x[0]===state.view)?.[1]||'Portal';
  function login(){const acc=S.getAccounts().find(a=>a.role===role&&a.active!==false);root.innerHTML=`<section class="portal-login"><form class="login-card" id="portal-login"><img src="one-line-mark.svg" alt="One-Line"><p style="font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:var(--brand);font-weight:850">${S.esc(role)} portal</p><h1>Sign in</h1><p>Use the local demo account for this role.</p><div class="demo-note">Demo: <strong>${S.esc(acc?.username||role)}</strong> / <strong>${S.esc(acc?.password||'')}</strong></div><div class="field"><label>Username</label><input name="username" required autocomplete="username"></div><div class="field"><label>Password</label><input type="password" name="password" required autocomplete="current-password"></div><button class="btn btn-primary btn-wide" type="submit">Continue</button></form></section>`;root.querySelector('#portal-login').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),a=S.getAccounts().find(x=>x.role===role&&x.active!==false&&x.username===f.get('username')&&x.password===f.get('password'));if(a){sessionStorage.setItem(sessionKey,'1');render()}else alert('Incorrect username or password.');});}
  function sidebar(){return `<aside class="sidebar"><div class="sidebar-brand"><img src="one-line-mark.svg" alt=""><div>One-Line<div class="role-pill">${S.esc(role)}</div></div></div><nav class="side-nav">${allowed.map(([id,label,icon])=>`<button class="${state.view===id?'active':''}" data-view="${id}">${I(icon)} ${label}</button>`).join('')}</nav><div class="side-foot"><button class="btn btn-soft" data-logout>${I('logout')} Sign out</button></div></aside>`;}
  function mobileTabs(){return `<nav class="mobile-tabs">${allowed.map(([id,label])=>`<button class="${state.view===id?'active':''}" data-view="${id}">${label}</button>`).join('')}</nav>`;}
  function shell(content){root.innerHTML=`<div class="portal-shell">${sidebar()}<main class="portal-main"><header class="topbar"><div><h1>${S.esc(title())}</h1><span>${S.esc(role)} workspace</span></div><a class="btn btn-secondary btn-small" href="index.html">Store</a></header><div class="content">${content}</div></main></div>${mobileTabs()}${renderModal()}`;bindForms();}
  function stat(label,value){return `<div class="stat"><span>${S.esc(label)}</span><strong>${S.esc(value)}</strong></div>`;}
  function dashboard(){const ps=S.getProducts(),orders=S.getOrders();return `<div class="stats">${stat('Retail products',ps.filter(p=>p.audience==='retail').length)}${stat('B2B products',ps.filter(p=>p.audience==='b2b').length)}${stat('Orders',orders.length)}${stat('Cart data','Live')}</div><section class="panel"><div class="panel-head"><div><h2>Recent orders</h2><p>Orders created from the customer website appear here.</p></div></div>${orderCards(orders.slice(0,5))}</section>`;}
  function productTable(){const ps=S.getProducts();return `<section class="panel" style="margin-top:0"><div class="panel-head"><div><h2>Products</h2><p>Retail and B2B products use the same clean product editor.</p></div><button class="btn btn-primary" data-product-new>${I('plus')} Add product</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Image</th><th>Product</th><th>Audience</th><th>Category</th><th>Price</th><th>Stock</th><th>Actions</th></tr></thead><tbody>${ps.map(p=>`<tr><td><img src="${S.esc(p.image)}" alt=""></td><td><strong>${S.esc(p.name)}</strong><br><small>${S.esc(p.subcategory||'')}</small></td><td><span class="badge ${p.audience==='b2b'?'b2b':'retail'}">${S.esc(p.audience)}</span></td><td>${S.esc(p.category)}</td><td>${p.audience==='b2b'?'Enquiry':S.money(p.price)}</td><td>${Number(p.stock||0)}</td><td><div class="row-actions"><button class="btn btn-secondary btn-small" data-product-edit="${p.id}">${I('edit')} Edit</button><button class="btn btn-danger btn-small" data-product-delete="${p.id}">${I('trash')}</button></div></td></tr>`).join('')}</tbody></table></div></section>`;}
  function categories(){const cats=S.getCategories();return `<section class="panel" style="margin-top:0"><div class="panel-head"><div><h2>Categories</h2><p>These images appear as the large customer homepage cards.</p></div><button class="btn btn-primary" data-category-new>${I('plus')} Add category</button></div><div class="cards">${cats.map(c=>`<article class="entity-card"><img src="${S.esc(c.image)}" alt="${S.esc(c.name)}"><div class="entity-card-body"><h3>${S.esc(c.name)}</h3><p>${S.esc(c.subtitle||'')}</p><div class="row-actions"><button class="btn btn-secondary btn-small" data-category-edit="${c.id}">Edit</button><button class="btn btn-danger btn-small" data-category-delete="${c.id}">Delete</button></div></div></article>`).join('')}</div></section>`;}
  function customization(){const prints=S.getPrints();return `<div class="grid-two"><section class="panel" style="margin-top:0"><div class="panel-head"><div><h2>Print methods</h2><p>Used directly by the rebuilt customizer.</p></div></div>${prints.map(p=>`<div style="padding:12px 0;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:12px"><div><strong>${S.esc(p.name)}</strong><div class="order-meta">${S.esc(p.note)}</div></div><div><strong>${S.money(p.price)}</strong><br><button class="btn btn-secondary btn-small" data-print-edit="${p.id}">Edit</button></div></div>`).join('')}</section><section class="panel" style="margin-top:0"><div class="panel-head"><div><h2>Customizer garments</h2><p>Front, back and sleeve assets are built into the clean editor.</p></div></div><div class="order-card"><strong>T-Shirt</strong><div class="order-meta">Front · Back · Both sleeves</div></div><div class="order-card"><strong>Sportswear</strong><div class="order-meta">Front · Back · Both sleeves</div></div><div class="order-card"><strong>Polo</strong><div class="order-meta">Front · Back · Both sleeves</div></div></section></div>`;}
  function orderCards(orders=S.getOrders()){if(!orders.length)return'<div class="empty">No orders yet.</div>';const statuses=['Confirmed','Packed','Shipped','Delivered','Cancelled'];return orders.map(o=>`<article class="order-card"><div class="order-head"><div><h3>${S.esc(o.id)} · ${S.esc(o.customer?.name||'Customer')}</h3><div class="order-meta">${S.esc(o.customer?.phone||'')} · ${new Date(o.createdAt).toLocaleString()}</div></div><strong>${S.money(o.total)}</strong></div><div class="order-lines">${(o.items||[]).map(i=>`${S.esc(i.name)} × ${i.qty}`).join(' · ')}</div><div class="order-meta" style="margin-bottom:10px">${S.esc(o.customer?.address||'')} · ${S.esc(o.customer?.delivery||'')}</div><div class="order-status">${statuses.map(s=>`<button class="${o.status===s?'active':''}" data-order-status="${o.id}" data-status="${s}">${s}</button>`).join('')}</div></article>`).join('');}
  function orders(){return `<section class="panel" style="margin-top:0"><div class="panel-head"><div><h2>Order receiving</h2><p>Update the status from confirmed through delivery.</p></div></div>${orderCards()}</section>`;}
  function stock(){const ps=S.getProducts().filter(p=>p.audience==='retail');return `<section class="panel" style="margin-top:0"><div class="panel-head"><div><h2>Stock desk</h2><p>Quick stock adjustment for sales staff.</p></div></div><div class="stock-grid">${ps.map(p=>`<article class="stock-card"><img src="${S.esc(p.image)}" alt=""><div><h3>${S.esc(p.name)}</h3><p>${S.esc(p.category)}</p></div><div class="stock-controls"><button data-stock="${p.id}" data-delta="-1">−</button><strong>${Number(p.stock||0)}</strong><button data-stock="${p.id}" data-delta="1">+</button></div></article>`).join('')}</div></section>`;}
  function accounts(){const acc=S.getAccounts();return `<section class="panel" style="margin-top:0"><div class="panel-head"><div><h2>Portal accounts</h2><p>Local demo credentials only. Replace with server-side authentication for production.</p></div><button class="btn btn-primary" data-account-new>${I('plus')} Add account</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Role</th><th>Username</th><th>Status</th><th>Actions</th></tr></thead><tbody>${acc.map(a=>`<tr><td><strong>${S.esc(a.name)}</strong></td><td>${S.esc(a.role)}</td><td>${S.esc(a.username)}</td><td><span class="badge ${a.active!==false?'ok':'off'}">${a.active!==false?'Active':'Suspended'}</span></td><td><button class="btn btn-secondary btn-small" data-account-toggle="${a.id}">${a.active!==false?'Suspend':'Activate'}</button></td></tr>`).join('')}</tbody></table></div></section>`;}
  function settings(){const s=S.getSettings();return `<section class="panel" style="margin-top:0;max-width:760px"><div class="panel-head"><div><h2>Store settings</h2><p>Contact and B2B access settings used by the customer pages.</p></div></div><form id="settings-form"><div class="form-grid"><div class="field full"><label>WhatsApp number</label><input name="whatsapp" value="${S.esc(s.whatsapp||'')}" placeholder="919876543210"><div class="help">Country code + number. Leave blank to let WhatsApp ask the customer where to send.</div></div><div class="field"><label>B2B ID</label><input name="b2bId" value="${S.esc(s.b2bId||'')}"></div><div class="field"><label>B2B password</label><input name="b2bPassword" value="${S.esc(s.b2bPassword||'')}"></div></div><button class="btn btn-primary" type="submit">Save settings</button></form></section>`;}
  function renderContent(){if(state.view==='dashboard')return dashboard();if(state.view==='products')return productTable();if(state.view==='categories')return categories();if(state.view==='customization')return customization();if(state.view==='orders')return orders();if(state.view==='stock')return stock();if(state.view==='accounts')return accounts();if(state.view==='settings')return settings();return dashboard();}
  function renderModal(){if(!state.modal)return'';if(state.modal==='product')return productModal();if(state.modal==='category')return categoryModal();if(state.modal==='print')return printModal();if(state.modal==='account')return accountModal();return'';}
  function productModal(){const p=state.editing||{id:'',name:'',audience:'retail',category:S.getCategories()[0]?.name||'',subcategory:'',price:0,mrp:0,image:'assets/crew-tee.webp',type:'Colour + Option',optionTitle:'Size',colors:['Black','White'],sizes:['S','M','L','XL'],stock:0,description:'',keywords:'',active:true};return `<div class="modal-backdrop" data-modal-backdrop><div class="modal"><div class="modal-head"><h2>${p.id?'Edit product':'Add product'}</h2><button class="modal-close" data-modal-close>${I('close')}</button></div><form id="product-form"><input type="hidden" name="id" value="${S.esc(p.id)}"><div class="form-grid"><div class="field full"><label>Name</label><input name="name" required value="${S.esc(p.name)}"></div><div class="field"><label>Audience</label><select name="audience"><option value="retail" ${p.audience==='retail'?'selected':''}>Retail</option><option value="b2b" ${p.audience==='b2b'?'selected':''}>B2B</option></select></div><div class="field"><label>Category</label><select name="category">${S.getCategories().map(c=>`<option ${p.category===c.name?'selected':''}>${S.esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Subcategory</label><input name="subcategory" value="${S.esc(p.subcategory||'')}"></div><div class="field"><label>Product type</label><select name="type"><option ${p.type==='Simple'?'selected':''}>Simple</option><option ${p.type==='One Option'?'selected':''}>One Option</option><option ${p.type==='Colour + Option'?'selected':''}>Colour + Option</option></select></div><div class="field"><label>Price</label><input name="price" type="number" min="0" value="${Number(p.price||0)}"></div><div class="field"><label>MRP</label><input name="mrp" type="number" min="0" value="${Number(p.mrp||0)}"></div><div class="field"><label>Stock</label><input name="stock" type="number" min="0" value="${Number(p.stock||0)}"></div><div class="field full"><label>Product image</label><input name="image" id="product-image-value" value="${S.esc(p.image||'')}" placeholder="Asset path or image URL"><input id="product-image-file" type="file" accept="image/*"><div class="help">Choose a file or keep an asset path/URL. Uploaded images are stored locally in this static demo.</div></div><div class="field"><label>Colours</label><input name="colors" value="${S.esc((p.colors||[]).join(', '))}" placeholder="Black, White, Olive"></div><div class="field"><label>Options / sizes</label><input name="sizes" value="${S.esc((p.sizes||[]).join(', '))}" placeholder="S, M, L, XL"></div><div class="field"><label>Option label</label><input name="optionTitle" value="${S.esc(p.optionTitle||'Size')}"></div><div class="field"><label>Keywords</label><input name="keywords" value="${S.esc(p.keywords||'')}"></div><div class="field full"><label>Description</label><textarea name="description">${S.esc(p.description||'')}</textarea></div></div><button class="btn btn-primary btn-wide" type="submit">Save product</button></form></div></div>`;}
  function categoryModal(){const c=state.editing||{id:'',name:'',subtitle:'',image:'assets/category-tshirts.webp',active:true,order:S.getCategories().length+1};return `<div class="modal-backdrop" data-modal-backdrop><div class="modal"><div class="modal-head"><h2>${c.id?'Edit category':'Add category'}</h2><button class="modal-close" data-modal-close>${I('close')}</button></div><form id="category-form"><input type="hidden" name="id" value="${S.esc(c.id)}"><div class="field"><label>Name</label><input name="name" required value="${S.esc(c.name)}"></div><div class="field"><label>Subtitle</label><input name="subtitle" value="${S.esc(c.subtitle||'')}"></div><div class="field"><label>Category image</label><input name="image" id="category-image-value" value="${S.esc(c.image||'')}" placeholder="Asset path or image URL"><input id="category-image-file" type="file" accept="image/*"></div><button class="btn btn-primary btn-wide" type="submit">Save category</button></form></div></div>`;}
  function printModal(){const p=state.editing;return `<div class="modal-backdrop" data-modal-backdrop><div class="modal"><div class="modal-head"><h2>Edit print method</h2><button class="modal-close" data-modal-close>${I('close')}</button></div><form id="print-form"><input type="hidden" name="id" value="${S.esc(p.id)}"><div class="field"><label>Name</label><input name="name" value="${S.esc(p.name)}" required></div><div class="field"><label>Price</label><input name="price" type="number" min="0" value="${Number(p.price||0)}"></div><div class="field"><label>Note</label><textarea name="note">${S.esc(p.note||'')}</textarea></div><label style="display:flex;gap:8px;align-items:center;margin-bottom:16px"><input type="checkbox" name="lightOnly" ${p.lightOnly?'checked':''}> Light colours only</label><button class="btn btn-primary btn-wide" type="submit">Save print method</button></form></div></div>`;}
  function accountModal(){return `<div class="modal-backdrop" data-modal-backdrop><div class="modal"><div class="modal-head"><h2>Add portal account</h2><button class="modal-close" data-modal-close>${I('close')}</button></div><form id="account-form"><div class="form-grid"><div class="field full"><label>Name</label><input name="name" required></div><div class="field"><label>Role</label><select name="role"><option>staff</option><option>management</option><option>receiver</option><option>admin</option></select></div><div class="field"><label>Username</label><input name="username" required></div><div class="field full"><label>Password</label><input name="password" required></div></div><button class="btn btn-primary btn-wide" type="submit">Create account</button></form></div></div>`;}
  function bindForms(){
    const bindImageFile=(fileSelector,valueSelector)=>{const file=root.querySelector(fileSelector),value=root.querySelector(valueSelector);file?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>4*1024*1024){alert('Please choose an image under 4 MB.');e.target.value='';return}const r=new FileReader();r.onload=()=>{if(value)value.value=r.result};r.readAsDataURL(f);});};
    bindImageFile('#product-image-file','#product-image-value');bindImageFile('#category-image-file','#category-image-value');
    root.querySelector('#settings-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),s=S.getSettings();S.setSettings({...s,whatsapp:f.get('whatsapp').trim(),b2bId:f.get('b2bId').trim(),b2bPassword:f.get('b2bPassword')});alert('Settings saved.');});
    root.querySelector('#product-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('id')||S.uid('P'),list=S.getProducts(),old=list.find(x=>String(x.id)===String(f.get('id')))||{};const colors=String(f.get('colors')||'').split(',').map(x=>x.trim()).filter(Boolean),sizes=String(f.get('sizes')||'').split(',').map(x=>x.trim()).filter(Boolean),image=f.get('image').trim();const p={...old,id,name:f.get('name').trim(),audience:f.get('audience'),category:f.get('category'),subcategory:f.get('subcategory').trim(),price:Number(f.get('price')||0),mrp:Number(f.get('mrp')||0),stock:Number(f.get('stock')||0),image,images:[image],type:f.get('type'),optionTitle:f.get('optionTitle').trim()||'Size',colors,sizes,description:f.get('description').trim(),keywords:f.get('keywords').trim(),active:true};p.colorVariants=colors.map(c=>({color:c,image,sizes:[...sizes],stock:Object.fromEntries(sizes.map(s=>[s,Math.max(0,Math.floor(p.stock/Math.max(1,sizes.length*colors.length)))]))}));const i=list.findIndex(x=>String(x.id)===String(id));if(i>=0)list[i]=p;else list.push(p);S.setProducts(list);closeModal();render();});
    root.querySelector('#category-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('id')||S.uid('CAT'),list=S.getCategories(),old=list.find(x=>String(x.id)===String(f.get('id')))||{};const c={...old,id,name:f.get('name').trim(),subtitle:f.get('subtitle').trim(),image:f.get('image').trim(),active:true,order:old.order||list.length+1};const i=list.findIndex(x=>String(x.id)===String(id));if(i>=0)list[i]=c;else list.push(c);S.setCategories(list);closeModal();render();});
    root.querySelector('#print-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),list=S.getPrints(),i=list.findIndex(x=>x.id===f.get('id'));if(i>=0)list[i]={...list[i],name:f.get('name').trim(),price:Number(f.get('price')||0),note:f.get('note').trim(),lightOnly:f.get('lightOnly')==='on'};S.setPrints(list);closeModal();render();});
    root.querySelector('#account-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),list=S.getAccounts();if(list.some(x=>x.username===f.get('username').trim())){alert('Username already exists.');return}list.push({id:S.uid('ACC'),name:f.get('name').trim(),role:f.get('role'),username:f.get('username').trim(),password:f.get('password'),active:true});S.setAccounts(list);closeModal();render();});
  }
  function closeModal(){state.modal=null;state.editing=null;}
  root.addEventListener('click',e=>{
    const view=e.target.closest('[data-view]');if(view){state.view=view.dataset.view;render();return}
    if(e.target.closest('[data-logout]')){sessionStorage.removeItem(sessionKey);login();return}
    if(e.target.closest('[data-modal-close]')||e.target.matches?.('[data-modal-backdrop]')){closeModal();render();return}
    if(e.target.closest('[data-product-new]')){state.modal='product';state.editing=null;render();return}
    const pe=e.target.closest('[data-product-edit]');if(pe){state.modal='product';state.editing=S.productById(pe.dataset.productEdit);render();return}
    const pd=e.target.closest('[data-product-delete]');if(pd&&confirm('Delete this product?')){S.setProducts(S.getProducts().filter(p=>String(p.id)!==String(pd.dataset.productDelete)));render();return}
    if(e.target.closest('[data-category-new]')){state.modal='category';state.editing=null;render();return}
    const ce=e.target.closest('[data-category-edit]');if(ce){state.modal='category';state.editing=S.getCategories().find(c=>String(c.id)===String(ce.dataset.categoryEdit));render();return}
    const cd=e.target.closest('[data-category-delete]');if(cd&&confirm('Delete this category?')){S.setCategories(S.getCategories().filter(c=>String(c.id)!==String(cd.dataset.categoryDelete)));render();return}
    const pr=e.target.closest('[data-print-edit]');if(pr){state.modal='print';state.editing=S.getPrints().find(p=>p.id===pr.dataset.printEdit);render();return}
    if(e.target.closest('[data-account-new]')){state.modal='account';state.editing=null;render();return}
    const at=e.target.closest('[data-account-toggle]');if(at){const list=S.getAccounts(),a=list.find(x=>x.id===at.dataset.accountToggle);if(a)a.active=!a.active;S.setAccounts(list);render();return}
    const os=e.target.closest('[data-order-status]');if(os){S.updateOrder(os.dataset.orderStatus,{status:os.dataset.status});render();return}
    const st=e.target.closest('[data-stock]');if(st){const list=S.getProducts(),p=list.find(x=>String(x.id)===String(st.dataset.stock));if(p)p.stock=Math.max(0,Number(p.stock||0)+Number(st.dataset.delta));S.setProducts(list);render();return}
  });
  function render(){if(!logged()){login();return}shell(renderContent());}
  window.addEventListener('one-line-data',()=>{if(logged()&&!state.modal)render();});
  render();
})();
