(function(){
  "use strict";
  const S=window.OneLineStore,I=S.icon,root=document.getElementById('receiver-app');
  const state={orders:S.getOrders(),filter:'All',query:'',selected:null};
  const filters=['All','Confirmed','Packed','Ready','Shipped','Delivered'];
  function orderCard(o){const custom=o.orderItems?.find(x=>x.customDesign);return '<article class="order-card" data-open-order="'+S.esc(o.id)+'"><div class="order-card-top"><div><i class="status-mark '+o.status.toLowerCase()+'"></i>'+S.esc(o.status)+'</div><time>'+I('clock')+S.esc(o.time)+'</time></div><div class="order-id"><span>ORDER REFERENCE</span><strong>#'+S.esc(o.id)+'</strong></div><div class="order-customer"><b>'+S.esc(o.customer)+'</b><span>'+I('phone')+S.esc(o.phone)+'</span></div>'+(custom?'<div class="receiver-item-previews">'+S.designedSurfaces(custom.customDesign).slice(0,4).map(face=>S.designPreview(custom.customDesign,face)).join('')+'<span>EXACT DESIGN ATTACHED</span></div>':'')+'<div class="order-facts"><div><small>ITEMS</small><b>'+o.items+'</b></div><div><small>DELIVERY</small><b>'+S.esc(o.delivery)+'</b></div><div><small>PAYMENT</small><b>'+S.esc(o.payment)+'</b></div></div><div class="order-card-bottom"><strong>'+S.money(o.total)+'</strong><button>View order '+I('arrow')+'</button></div></article>';}
  function productionLayers(design,face){
    const d=S.surfaceDesign(design,face),layers=Array.isArray(d.layers)&&d.layers.length?d.layers:[];
    if(!layers.length){
      if(d.text)layers.push({type:'text',value:d.text,font:d.font,color:d.textColor,size:d.textSize,rotation:d.textRotation,position:d.positions?.text});
      if(d.uploadedImage)layers.push({type:'image',src:d.uploadedImage,size:d.imageSize,rotation:d.imageRotation,position:d.positions?.image});
    }
    let textN=0,imageN=0;
    return layers.map(layer=>{
      const pos=layer.position||{x:50,y:50};
      if(layer.type==='image'){
        imageN++;
        return '<div class="receiver-layer-spec"><img src="'+S.esc(layer.src||'')+'" alt="Uploaded production artwork"><span><b>Image '+imageN+'</b> · '+Math.round(Number(layer.size||0))+'px · '+Math.round(Number(layer.rotation||0))+'°</span><small>Position '+Math.round(Number(pos.x||50))+'% × '+Math.round(Number(pos.y||50))+'%</small></div>';
      }
      textN++;
      return '<div class="receiver-layer-spec"><span><b>Text '+textN+':</b> '+S.esc(layer.value||'')+'</span><small>'+S.esc(layer.font||'')+' · '+Math.round(Number(layer.size||0))+'px · '+Math.round(Number(layer.rotation||0))+'° · Position '+Math.round(Number(pos.x||50))+'% × '+Math.round(Number(pos.y||50))+'%</small></div>';
    }).join('')||'<span>No artwork layers on this side.</span>';
  }
  function itemDetail(item){const previews=item.customDesign?'<div class="design-surface-gallery">'+S.designedSurfaces(item.customDesign).map(face=>'<figure>'+S.designPreview(item.customDesign,face)+'<figcaption>'+face.replace('Sleeve',' sleeve')+'</figcaption></figure>').join('')+'</div>':'<img src="'+S.esc(item.image||'assets/crew-tee.webp')+'" alt="">';return '<article>'+previews+'<div><span>'+(item.custom?'CUSTOMIZED PRODUCTION ITEM':'READY-MADE ITEM')+'</span><h4>'+S.esc(item.name)+'</h4><p>'+[item.color,item.size,item.detail,'Qty '+item.qty].filter(Boolean).map(S.esc).join(' · ')+'</p>'+(item.customDesign?'<div class="receiver-production-specs">'+S.designedSurfaces(item.customDesign).map(face=>'<section><b>'+face.replace('Sleeve',' sleeve')+'</b>'+productionLayers(item.customDesign,face)+'</section>').join('')+'</div>':'')+'</div><strong>'+S.money(item.price*item.qty)+'</strong></article>';}

  function drawer(){const o=state.selected;if(!o)return '';return '<div class="overlay receiver-overlay"><aside class="order-drawer"><div class="drawer-head"><div><span>ORDER DETAILS</span><h2>#'+S.esc(o.id)+'</h2></div><button data-action="close">'+I('close')+'</button></div><div class="drawer-status"><i class="status-mark '+o.status.toLowerCase()+'"></i><div><small>CURRENT STATUS</small><b>'+S.esc(o.status)+'</b></div><time>'+S.esc(o.time)+'</time></div><section class="drawer-section"><span>CUSTOMER</span><h3>'+S.esc(o.customer)+'</h3><p>'+I('phone')+S.esc(o.phone)+'</p><p>'+I('map')+S.esc(o.address)+'</p></section><section class="drawer-section receiver-detailed-items"><span>ORDERED ITEMS & PRODUCTION FILES</span>'+(o.orderItems?.length?o.orderItems.map(itemDetail).join(''):'<div class="legacy-order-note">'+I('package')+'<span><b>'+o.items+' items</b><small>This seeded demonstration order does not contain item-level artwork.</small></span></div>')+'</section><section class="drawer-section"><div class="detail-grid"><div><span>DELIVERY</span><b>'+I('truck')+S.esc(o.delivery)+'</b></div><div><span>PAYMENT</span><b>'+I('card')+S.esc(o.payment)+'</b></div></div></section><div class="drawer-total"><span>ORDER TOTAL</span><strong>'+S.money(o.total)+'</strong></div><div class="order-actions">'+['Packed','Ready','Shipped','Delivered'].map(x=>'<button class="'+(x==='Delivered'?'receiver-primary':'')+'" data-status="'+x+'">'+(x==='Delivered'?I('check'):'')+x+'</button>').join('')+'<button class="danger" data-status="Cancelled">Cancel</button></div></aside></div>';}
  function render(){state.orders=S.getOrders();const list=state.orders.filter(o=>(state.filter==='All'||o.status===state.filter)&&(!state.query||(o.id+' '+o.customer+' '+o.phone).toLowerCase().includes(state.query.toLowerCase())));root.innerHTML='<div class="receiver-shell"><header class="receiver-header"><div class="receiver-logo"><img src="one-line-logo.webp" alt=""><div><b>One-Line</b><small>ORDER RECEIVING</small></div></div><div class="receiver-live"><i></i> LIVE ORDER FEED</div><div><span>Production desk</span><a href="admin.html">Admin panel</a></div></header><main class="receiver-main"><div class="receiver-title"><div><span>CONFIRMED CUSTOMER ORDERS</span><h1>Order board <sup>'+list.length+'</sup></h1><p>Open an order to see exact custom images, uploaded files, fonts, rotation and print surfaces.</p></div><div class="receiver-metrics"><article><b>'+state.orders.filter(o=>o.status==='Confirmed').length+'</b><span>NEW</span></article><article><b>'+state.orders.filter(o=>['Packed','Ready','Shipped'].includes(o.status)).length+'</b><span>IN PROGRESS</span></article><article><b>'+state.orders.filter(o=>o.status==='Delivered').length+'</b><span>DONE</span></article></div></div><div class="receiver-tools"><label>'+I('search')+'<input data-search value="'+S.esc(state.query)+'" placeholder="Order, customer or phone"></label><div>'+filters.map(f=>'<button class="'+(state.filter===f?'active':'')+'" data-filter="'+f+'">'+f+' <span>'+state.orders.filter(o=>f==='All'||o.status===f).length+'</span></button>').join('')+'</div></div><section class="order-board">'+(list.length?list.map(orderCard).join(''):'<div class="empty-state">'+I('orders')+'<h2>No orders here</h2><p>New confirmed orders will appear automatically.</p></div>')+'</section></main>'+drawer()+'</div>';bind();}
  function bind(){root.querySelectorAll('[data-filter]').forEach(x=>x.addEventListener('click',()=>{state.filter=x.dataset.filter;render();}));root.querySelectorAll('[data-open-order]').forEach(x=>x.addEventListener('click',()=>{state.selected=state.orders.find(o=>o.id===x.dataset.openOrder);render();}));root.querySelectorAll('[data-action="close"]').forEach(x=>x.addEventListener('click',()=>{state.selected=null;render();}));root.querySelectorAll('[data-status]').forEach(x=>x.addEventListener('click',()=>{const next=state.orders.map(o=>o.id===state.selected.id?Object.assign({},o,{status:x.dataset.status}):o);S.save('custom-store-orders-v3',next);state.selected=next.find(o=>o.id===state.selected.id);render();}));const q=root.querySelector('[data-search]');if(q)q.addEventListener('input',()=>{state.query=q.value;render();const n=root.querySelector('[data-search]');n?.focus();try{n?.setSelectionRange(state.query.length,state.query.length);}catch(_){}});}
  window.addEventListener('storage',render);window.addEventListener('one-line-change',render);render();
})();
