(function(){
"use strict";
const S=window.OneLineStore,I=S.icon,root=document.getElementById("staff-app");
const state={session:S.getSession("admin"),tab:"orders",error:"",query:"",selected:null,orderItems:[],toast:"",productModal:false,editing:null};
function data(){return{products:S.getProducts(),orders:S.getOrders(),settings:S.getSettings()};}
function login(){root.innerHTML='<main class="portal-login-page"><section class="portal-login"><div>'+I("lock")+'<span>ORDER RECEIVING</span><h1>Production desk.</h1><p>Review production artwork, direct orders and order status.</p></div><form data-login><label>Username<input required name="username"></label><label>Password<input required name="password" type="password"></label>'+(state.error?'<p class="login-error">'+S.esc(state.error)+'</p>':'')+'<button>Sign in</button><small>Demo: admin / admin123</small></form></section></main>';root.querySelector("[data-login]").addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),a=S.authenticate("admin",f.get("username"),f.get("password"));if(!a){state.error="Incorrect login or this staff account is blocked.";login();return;}state.session=S.setSession(a);render();});}
function header(d){return '<header class="staff-header"><div class="receiver-logo"><img src="one-line-mark.svg"><div><b>'+S.esc(d.settings.storeName)+'</b><small>ORDER RECEIVING</small></div></div><nav>'+[["orders","Order board"],["direct","Place direct order"]].map(x=>'<button data-tab="'+x[0]+'" class="'+(state.tab===x[0]?"active":"")+'">'+x[1]+'</button>').join("")+'</nav><div><span>'+S.esc(state.session.name)+'</span><a href="index.html">Store</a><button data-action="logout">'+I("logout")+'</button></div></header>';}
function orderCard(o){const custom=o.orderItems?.find(x=>x.customDesign);return '<article class="order-card" data-order="'+S.esc(o.id)+'"><div class="order-card-top"><div><i class="status-mark '+o.status.toLowerCase()+'"></i>'+S.esc(o.status)+'</div><time>'+I("clock")+S.timeAgo(o.createdAt)+'</time></div><div class="order-id"><span>ORDER REFERENCE</span><strong>#'+S.esc(o.id)+'</strong></div><div class="order-customer"><b>'+S.esc(o.customer)+'</b><span>'+I("phone")+S.esc(o.phone)+'</span></div>'+(custom?'<div class="receiver-item-previews">'+S.designedSurfaces(custom.customDesign).slice(0,4).map(f=>S.designPreview(custom.customDesign,f)).join("")+'<span>DESIGN ATTACHED</span></div>':'')+'<div class="order-facts"><div><small>PIECES</small><b>'+o.items+'</b></div><div><small>CHANNEL</small><b>'+S.esc(o.channel||"Customer")+'</b></div><div><small>DELIVERY</small><b>'+S.esc(o.delivery)+'</b></div></div><div class="order-card-bottom"><strong>'+S.money(o.total)+'</strong><button>Open '+I("arrow")+'</button></div></article>';}
function orders(d){const q=state.query.toLowerCase(),list=d.orders.filter(o=>(o.id+" "+o.customer+" "+o.phone).toLowerCase().includes(q));return '<main class="receiver-main staff-main"><div class="receiver-title"><div><span>LIVE PRODUCTION QUEUE</span><h1>Orders <sup>'+list.length+'</sup></h1><p>Open an order to review exact artwork and move production forward.</p></div><button class="admin-primary" data-tab="direct">'+I("plus")+' Direct order</button></div><div class="receiver-tools"><label>'+I("search")+'<input data-search value="'+S.esc(state.query)+'" placeholder="Order, customer or phone"></label></div><section class="order-board">'+list.map(orderCard).join("")+'</section></main>';}
function direct(d){const matches=d.products.filter(p=>!p.customSection&&p.active&&S.matches(p,{},state.query,true)).slice(0,8),sum=state.orderItems.reduce((n,x)=>n+x.price*x.qty,0);return '<main class="staff-content"><div class="staff-page-head"><div><span>PHONE / WALK-IN / WHATSAPP</span><h1>Place direct order</h1></div></div><div class="direct-order-layout"><section class="admin-panel direct-picker"><label class="direct-search">'+I("barcode")+'<input data-direct-search value="'+S.esc(state.query)+'" placeholder="Scan barcode or search product"></label><div class="direct-products">'+matches.map(p=>'<article data-direct-row="'+p.id+'"><img src="'+S.esc(p.image)+'"><span><b>'+S.esc(p.name)+'</b><small>'+S.esc(p.sku)+' · Stock '+p.stock+'</small></span><select data-direct-color>'+((p.colors?.length?p.colors:["Default"]).map(c=>'<option>'+S.esc(c)+'</option>').join(""))+'</select><select data-direct-size>'+((p.sizes?.length?p.sizes:["Default"]).map(s=>'<option>'+S.esc(s)+'</option>').join(""))+'</select><button data-add-direct="'+p.id+'">'+I("plus")+'</button></article>').join("")+'</div></section><section class="admin-panel direct-cart"><div class="panel-head"><div><span>DIRECT ORDER</span><h2>Selected items</h2></div></div><div class="direct-items">'+(state.orderItems.length?state.orderItems.map((x,i)=>'<article><div><b>'+S.esc(x.name)+'</b><small>'+S.esc(x.color||"Default")+' · '+S.esc(x.size||"Default")+'</small></div><input data-direct-qty="'+i+'" type="number" min="1" max="'+x.stock+'" value="'+x.qty+'"><strong>'+S.money(x.price*x.qty)+'</strong><button data-remove-direct="'+i+'">'+I("trash")+'</button></article>').join(""):'<p>No items added.</p>')+'</div><form class="direct-details" data-direct-order><label>Customer name<input required name="customer"></label><label>Mobile number<input required name="phone" pattern="[0-9 +()-]{10,15}"></label><label>Address / note<textarea required name="address"></textarea></label><label>Delivery<select name="delivery">'+S.getDelivery().filter(x=>x.active).map(x=>'<option>'+S.esc(x.name)+'</option>').join("")+'</select></label><div class="direct-total"><span>Total</span><strong>'+S.money(sum)+'</strong></div><button class="admin-primary" '+(state.orderItems.length?"":"disabled")+'>Place order and reduce stock</button></form></section></div></main>';}
function itemDetail(item){return '<article>'+(item.customDesign?'<div class="design-surface-gallery">'+S.designedSurfaces(item.customDesign).map(f=>'<figure>'+S.designPreview(item.customDesign,f)+'<figcaption>'+f.replace("Sleeve"," sleeve")+'</figcaption></figure>').join("")+'</div>':'<img src="'+S.esc(item.image||"assets/crew-tee.webp")+'">')+'<div><b>'+S.esc(item.name)+'</b><p>'+S.esc([item.color,item.size,item.detail,"Qty "+item.qty].filter(Boolean).join(" · "))+'</p>'+(item.customDesign?'<div class="production-layer-list">'+S.designedSurfaces(item.customDesign).map(f=>'<section><strong>'+f.replace("Sleeve"," sleeve")+'</strong>'+S.surfaceDesign(item.customDesign,f).layers.map(l=>'<span>'+S.esc(l.type==="text"?l.text:"Image artwork")+' · '+S.esc(S.getPrints().find(p=>p.id===l.printId)?.name||l.printId)+'</span>').join("")+'</section>').join("")+'</div>':'')+'</div><strong>'+S.money(item.price*item.qty)+'</strong></article>';}
function drawer(){const o=state.selected;if(!o)return "";return '<div class="overlay receiver-overlay"><aside class="order-drawer"><div class="drawer-head"><div><span>ORDER DETAILS</span><h2>#'+S.esc(o.id)+'</h2></div><button data-action="close-order">'+I("close")+'</button></div><section class="drawer-section"><h3>'+S.esc(o.customer)+'</h3><p>'+I("phone")+S.esc(o.phone)+'</p><p>'+I("map")+S.esc(o.address)+'</p></section><section class="drawer-section receiver-detailed-items">'+(o.orderItems?.length?o.orderItems.map(itemDetail).join(""):'<p>No item-level files on this seeded order.</p>')+'</section><div class="drawer-total"><span>ORDER TOTAL</span><strong>'+S.money(o.total)+'</strong></div><div class="order-actions">'+["Confirmed","Packed","Ready","Shipped","Delivered"].map(x=>'<button data-status="'+x+'" class="'+(x==="Delivered"?"receiver-primary":"")+'">'+x+'</button>').join("")+'<button class="danger" data-status="Cancelled">Cancel</button></div></aside></div>';}
function render(){state.session=S.getSession("admin");if(!state.session)return login();const d=data(),content=state.tab==="orders"?orders(d):direct(d);root.innerHTML='<div class="receiver-shell">'+header(d)+content+drawer()+""+(state.toast?'<div class="toast">'+I("check")+S.esc(state.toast)+'</div>':"")+'</div>';bind(d);}
function toast(t){state.toast=t;render();setTimeout(()=>{state.toast="";render();},1800);}
function bind(d){
 root.querySelectorAll("[data-tab]").forEach(x=>x.addEventListener("click",()=>{state.tab=x.dataset.tab;state.query="";render();}));
 root.querySelectorAll("[data-action]").forEach(x=>x.addEventListener("click",()=>{const a=x.dataset.action;if(a==="logout"){S.setSession(null);state.session=null;login();}if(a==="close-order"){state.selected=null;render();}if(a==="new-product"){state.editing=null;state.productModal=true;render();}if(a==="close-product"){state.productModal=false;state.editing=null;render();}if(a==="save-stock"){d.products.forEach(p=>{p.price=Number(root.querySelector('[data-price="'+p.id+'"]')?.value??p.price);if(p.colourOptions?.length){p.colourOptions.forEach((v,i)=>{v.stock=Number(root.querySelector('[data-colour-stock="'+p.id+'-'+i+'"]')?.value??v.stock);v.price=Number(root.querySelector('[data-colour-price="'+p.id+'-'+i+'"]')?.value??v.price);});p.stock=p.colourOptions.reduce((n,v)=>n+Number(v.stock||0),0);}else if(p.variants?.length){p.variants.forEach((v,i)=>{v.stock=Number(root.querySelector('[data-variant-stock="'+p.id+'-'+i+'"]')?.value??v.stock);v.price=Number(root.querySelector('[data-variant-price="'+p.id+'-'+i+'"]')?.value??v.price);});p.stock=p.variants.reduce((n,v)=>n+Number(v.stock||0),0);}else p.stock=Number(root.querySelector('[data-stock="'+p.id+'"]')?.value??p.stock);});S.save(S.KEYS.products,d.products,state.session);toast("Stock and prices saved");}}));
 root.querySelector("[data-search]")?.addEventListener("input",e=>{state.query=e.target.value;render();root.querySelector("[data-search]")?.focus();});
 root.querySelector("[data-direct-search]")?.addEventListener("input",e=>{state.query=e.target.value;render();root.querySelector("[data-direct-search]")?.focus();});
 root.querySelectorAll("[data-order]").forEach(x=>x.addEventListener("click",()=>{state.selected=d.orders.find(o=>o.id===x.dataset.order);render();}));
 root.querySelectorAll("[data-status]").forEach(x=>x.addEventListener("click",()=>{const o=d.orders.find(o=>o.id===state.selected.id);o.status=x.dataset.status;S.save(S.KEYS.orders,d.orders,state.session);state.selected=o;render();}));
 root.querySelectorAll("[data-edit-product]").forEach(x=>x.addEventListener("click",()=>{state.editing=d.products.find(p=>String(p.id)===x.dataset.editProduct);state.productModal=true;render();}));
 root.querySelectorAll("[data-add-direct]").forEach(x=>x.addEventListener("click",()=>{const p=d.products.find(p=>String(p.id)===x.dataset.addDirect),row=x.closest("[data-direct-row]"),color=row.querySelector("[data-direct-color]").value.replace("Default",""),size=p.sizes.length?row.querySelector("[data-direct-size]").value:"",stock=S.productStock(p,color,size),price=S.productPrice(p,color,size);if(!stock)return toast("This variant is out of stock");const found=state.orderItems.find(i=>i.productId===p.id&&i.color===color&&i.size===size);if(found)found.qty=Math.min(found.stock,found.qty+1);else state.orderItems.push({key:"direct-"+p.id+"-"+color+"-"+size,productId:p.id,name:p.name,image:S.productImage(p,color,"front",size),color,size,price,stock,qty:1});render();}));
 root.querySelectorAll("[data-direct-qty]").forEach(x=>x.addEventListener("change",()=>{const i=state.orderItems[Number(x.dataset.directQty)];i.qty=Math.max(1,Math.min(i.stock,Number(x.value)||1));render();}));
 root.querySelectorAll("[data-remove-direct]").forEach(x=>x.addEventListener("click",()=>{state.orderItems.splice(Number(x.dataset.removeDirect),1);render();}));
 root.querySelector("[data-staff-image-file]")?.addEventListener("change",async e=>{try{const image=await S.compressImage(e.target.files?.[0]);root.querySelector("[data-staff-image-value]").value=image;root.querySelector("[data-staff-image-preview]").src=image;}catch(error){toast(error.message);}});
 root.querySelector('[data-direct-order]')?.addEventListener('submit',e=>{e.preventDefault();try{const actor=S.authorize(['admin']),f=Object.fromEntries(new FormData(e.target).entries());S.commitOrder({customer:f.customer,phone:f.phone,address:f.address,delivery:f.delivery,payment:'Counter / pending',status:'Confirmed',channel:'Admin counter',items:state.orderItems.reduce((n,x)=>n+x.qty,0),total:state.orderItems.reduce((n,x)=>n+x.price*x.qty,0),orderItems:state.orderItems},actor);state.orderItems=[];state.query='';state.tab='orders';toast('Direct order placed');}catch(error){toast(error.message);}});
 root.querySelector("[data-product-form]")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),id=f.get("id")||Date.now(),old=d.products.find(p=>String(p.id)===String(id))||{},p=Object.assign({},old,{id,name:f.get("name"),sku:f.get("sku"),category:f.get("category"),subcategory:f.get("subcategory"),price:Number(f.get("price")),mrp:Number(f.get("mrp")),stock:Number(f.get("stock")),image:f.get("image"),colors:String(f.get("colors")).split(",").map(x=>x.trim()).filter(Boolean),sizes:String(f.get("sizes")).split(",").map(x=>x.trim()).filter(Boolean),description:f.get("description"),active:f.has("active"),customizable:false,customSection:false,allowedFabricIds:[],allowedPrintIds:[],variants:old.variants||[],colourOptions:old.colourOptions||[],colorImages:old.colorImages||{}});S.save(S.KEYS.products,[p,...d.products.filter(x=>String(x.id)!==String(id))],state.session);state.productModal=false;state.editing=null;render();});
}
window.addEventListener("storage",render);render();
})();
