const {page,errors}=require('./smoke.cjs');const assert=require('node:assert/strict'),fs=require('fs');const results=[];
const dom=page('index.html'),w=dom.window,d=w.document,S=w.OneLineStore;
function check(name,fn){fn();results.push({name,status:'PASS'});}
function click(sel){const el=d.querySelector(sel);assert.ok(el,sel);el.click();}
function value(sel,v,event='input'){const el=d.querySelector(sel);assert.ok(el,sel);el.value=v;el.dispatchEvent(new w.Event(event,{bubbles:true}));}
function pointer(sel,type,id,x,y){const e=new w.Event(type,{bubbles:true,cancelable:true});Object.assign(e,{pointerId:id,clientX:x,clientY:y,button:0,pointerType:'touch'});d.querySelector(sel).dispatchEvent(e);}
w.HTMLElement.prototype.getBoundingClientRect=function(){if(this.matches('[data-print-area]'))return{x:0,y:0,left:0,top:0,width:180,height:250,right:180,bottom:250};return{x:0,y:0,left:0,top:0,width:100,height:30,right:100,bottom:30};};
click('[data-go="customize"]');
check('Customizer opens separately with four base models, cloth and print methods',()=>{assert.equal(d.querySelectorAll('[data-picker-product]').length,4);assert.ok(d.querySelector('[data-cloth-select]'));assert.ok(d.querySelector('[data-print="dtf"]'));assert.equal(d.querySelectorAll('[data-surface]').length,4);});
check('Cloth type and colour update and remain selected across surfaces',()=>{value('[data-cloth-select]','cloth-2','change');click('[data-custom-color="Maroon"]');for(const side of ['front','back','rightSleeve','leftSleeve']){click('[data-surface="'+side+'"]');assert.equal(d.querySelector('[data-cloth-select]').value,'cloth-2');assert.equal(d.querySelector('.garment-tint').style.background,'rgb(124, 38, 55)');assert.ok(d.querySelector('.garment-photo').src.includes(side.includes('Sleeve')?'crew-tee-sleeve':side==='back'?'crew-tee-back':'crew-tee.webp'));}assert.equal(d.querySelectorAll('.mirror-sleeve').length,0);click('[data-surface="rightSleeve"]');assert.equal(d.querySelectorAll('.mirror-sleeve').length,2);});
check('Add and edit multiple independent text objects',()=>{click('[data-surface="front"]');click('[data-action="add-text"]');value('[data-layer-text]','FIRST');click('[data-action="add-text"]');value('[data-layer-text]','SECOND');assert.equal(d.querySelectorAll('[data-design-layer]').length,2);const first=d.querySelectorAll('[data-design-layer]')[0];first.dispatchEvent(new w.MouseEvent('dblclick',{bubbles:true}));assert.equal(d.querySelector('[data-layer-text]').value,'FIRST');value('[data-layer-text]','EDITED FIRST');assert.match(d.querySelector('[data-design-layer]').textContent,/EDITED FIRST/);});
check('Double tap targets the exact text after deselection',()=>{pointer('[data-stage]','pointerdown',1,10,10);assert.equal(d.querySelectorAll('.active-layer-editor').length,0);let layer=d.querySelectorAll('[data-design-layer]')[1],id=layer.dataset.designLayer,sel='[data-design-layer="'+id+'"]';pointer(sel,'pointerdown',1,90,100);pointer(sel,'pointerup',1,90,100);pointer(sel,'pointerdown',2,90,100);pointer(sel,'pointerup',2,90,100);assert.equal(d.querySelector('[data-layer-text]').value,'SECOND');assert.equal(d.activeElement,d.querySelector('[data-layer-text]'));value('[data-layer-text]','SECOND UPDATED');});
check('Drag preserves grab offset and moves selected item',()=>{const sel='[data-design-layer].selected',before=d.querySelector(sel).style.left;pointer(sel,'pointerdown',11,80,100);pointer(sel,'pointermove',11,98,125);pointer(sel,'pointerup',11,98,125);assert.notEqual(d.querySelector(sel).style.left,before);});
check('Two-pointer pinch resizes and rotates the object',()=>{const sel='[data-design-layer].selected',old=parseFloat(d.querySelector(sel).style.fontSize);pointer(sel,'pointerdown',21,40,100);pointer(sel,'pointerdown',22,80,100);pointer(sel,'pointermove',22,100,130);pointer(sel,'pointerup',21,40,100);pointer(sel,'pointerup',22,100,130);assert.ok(parseFloat(d.querySelector(sel).style.fontSize)>old);assert.ok(!d.querySelector(sel).style.transform.includes('rotate(0deg)'));});
check('Text font, colour, size and rotation controls update selected object',()=>{value('[data-font-select]','Georgia','change');value('[data-text-colour]','#123456');value('[data-layer-range="size"]','24');value('[data-layer-range="rotation"]','30');const el=d.querySelector('[data-design-layer].selected');assert.equal(el.style.fontFamily,'Georgia');assert.equal(el.style.color,'rgb(18, 52, 86)');assert.match(el.style.transform,/30deg/);});
check('Each view keeps its independent text design',()=>{for(const side of ['back','rightSleeve','leftSleeve']){click('[data-surface="'+side+'"]');click('[data-action="add-text"]');value('[data-layer-text]',side.toUpperCase());}click('[data-surface="front"]');assert.equal(d.querySelectorAll('[data-design-layer]').length,2);});
check('Saved cart design retains exact hex, cloth, print and all four sides',()=>{click('[data-print="dtf"]');click('[data-action="add"]');const item=S.getCart().find(x=>x.custom);assert.ok(item);assert.equal(item.customDesign.garmentHex,'#7c2637');assert.equal(item.customDesign.fabricId,'cloth-2');assert.equal(item.customDesign.printId,'dtf');assert.equal(S.designedSurfaces(item.customDesign).length,4);assert.equal(item.customDesign.surfaceDesigns.front.layers.length,2);assert.equal(item.customDesign.surfaceDesigns.front.layers[0].text,'EDITED FIRST');assert.match(S.designPreview(item.customDesign,'front'),/#7c2637/);});
check('Removal only deletes selected object',()=>{click('[data-go="customize"]');click('[data-action="add-text"]');click('[data-action="add-text"]');click('[data-remove-layer]');assert.equal(d.querySelectorAll('[data-design-layer]').length,1);});
check('Light-only print is disabled for dark hex colours',()=>{click('[data-custom-color="Black"]');assert.equal(d.querySelector('[data-print="sublimation"]').disabled,true);click('[data-custom-color="White"]');assert.equal(d.querySelector('[data-print="sublimation"]').disabled,false);});
check('Filter dialog renders all groups, resets and applies with loading state',()=>{click('[data-action="back"]');});
// Test filter UI independently, without relying on browser navigation in jsdom.
let applied;w.OneLineFilters.open(S.getProducts().filter(p=>!p.customSection),{},v=>applied=v);assert.equal(d.querySelectorAll('.filter-panel fieldset').length,5);
const checkbox=d.querySelector('[data-filter="sizes"][value="M"]');checkbox.checked=true;checkbox.dispatchEvent(new w.Event('change'));d.querySelector('.filter-panel form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.ok(d.querySelector('.filter-loading'));
setTimeout(()=>{assert.deepEqual(Array.from(applied.sizes),['M']);results.push({name:'Filter apply callback receives selected sizes and loader closes',status:'PASS'});assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync('qa/designer-results.json',JSON.stringify(results,null,2));console.log(results.map(r=>r.status+' '+r.name).join('\n'));dom.window.close();},220);
