const {page,errors}=require('./smoke.cjs');const assert=require('node:assert/strict'),fs=require('fs');const results=[];
function pass(name,fn){try{fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.stack});throw e;}}
const dom=page('admin.html'),w=dom.window,d=w.document,S=w.OneLineStore;
const find=(sel)=>{let el=d.querySelector(sel);assert.ok(el,'Missing '+sel);return el};
const click=(sel)=>find(sel).click();const fill=(sel,value)=>{const el=find(sel);el.value=String(value);el.dispatchEvent(new w.Event('input',{bubbles:true}));};const change=(sel,value)=>{const el=find(sel);if(el.type==='checkbox')el.checked=value;else el.value=value;el.dispatchEvent(new w.Event('change',{bubbles:true}));};const submit=sel=>find(sel).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
function addProduct(type,sku){click('[data-action="new-product"]');change('[name="categoryId"]','cat-tshirts');change('[name="subcategoryId"]','cat-tshirts-sub-0');fill('[name="name"]','Test '+sku);fill('[name="sku"]',sku);fill('[name="keywords"]','v strap, cotton, office shirt');fill('[name="price"]','500');change('[name="productType"]',type);}
function saveImageInForm(){// Add an existing product image through a real editor input event in upload-specific test below.
  // This setup uses the same public product save boundary, then edits through UI.
}
pass('Admin login rejects wrong password',()=>{fill('[name="username"]','admin');fill('[name="password"]','wrong');submit('[data-login]');assert.match(d.body.textContent,/Incorrect login/)});
pass('Admin login and dashboard',()=>{fill('[name="username"]','admin');fill('[name="password"]','admin123');submit('[data-login]');assert.ok(d.querySelector('[data-tab="products"]'))});
pass('All admin sections render',()=>{for(const tab of ['products','stock','catalog','subcategories','customizable','fabrics','custom','staff-accounts','management-accounts','b2b-accounts','users','orders','callbacks','bulk','settings','audit'])click('[data-tab="'+tab+'"]');click('[data-tab="products"]')});
pass('Simple product fields and dependent category',()=>{addProduct('simple','TEST-SIMPLE');assert.equal(find('[name="subcategoryId"]').value,'cat-tshirts-sub-0');assert.ok(!d.querySelector('[data-group-values]'));fill('[name="stock"]',10);change('[name="barcodeEnabled"]',true);fill('[name="barcode"]','TEST001');});
pass('Simple product requires image',()=>{submit('[data-ready-product-form]');assert.match(d.body.textContent,/Add a main product image/);click('[data-cancel]')});
let base=S.getProducts().find(p=>p.id===1),simple;
pass('Save and edit simple product through shared data layer',()=>{simple=S.saveProduct({...base,id:'test-simple',sku:'TEST-SIMPLE',name:'Simple test',productType:'simple',stock:10,price:500,barcode:'TEST001',colors:[],sizes:[],variants:[],gallery:[base.image],keywords:['v strap']});assert.equal(simple.variants.length,0);click('[data-tab="products"]');click('[data-edit-product="test-simple"]');fill('[name="price"]',550);submit('[data-ready-product-form]');assert.equal(S.getProducts().find(p=>p.id==='test-simple').price,550)});
pass('One Option form preserves independent images, barcodes and stock',()=>{click('[data-edit-product="test-simple"]');change('[name="productType"]','option');fill('[name="optionName"]','Type');fill('[data-group-values]','Regular, Slim');fill('[data-group-qty]',5);fill('[data-group-price]',550);click('[data-add-group]');const rows=d.querySelectorAll('[data-variant-row]');assert.equal(rows.length,2);fill('[data-variant-row]:first-child [data-v="barcode"]','REG-001');fill('[data-variant-row]:last-child [data-v="barcode"]','SLIM-001');submit('[data-ready-product-form]');const p=S.getProducts().find(p=>p.id==='test-simple');assert.equal(p.productType,'option');assert.equal(p.stock,10);assert.equal(p.optionName,'Type');assert.equal(S.productStock(p,'','Slim'),5);assert.equal(S.productStock(p,'','NotReal'),0)});
pass('Colour + Option creates exact combinations and editing keeps stock',()=>{click('[data-edit-product="1"]');const count=d.querySelectorAll('[data-variant-row]').length;assert.equal(count,25);fill('[data-variant-row]:first-child [data-v="stock"]',11);submit('[data-ready-product-form]');let p=S.getProducts().find(p=>p.id===1);assert.equal(p.variants.length,25);assert.equal(p.stock,203)});
pass('Reject duplicate product and variant barcodes',()=>{assert.throws(()=>S.saveProduct({...simple,id:'duplicate',sku:'DUP',barcode:'TEST001'}),/barcode/i)});
pass('Create category, image reference and subcategory through forms',()=>{click('[data-tab="catalog"]');click('[data-action="add-category"]');fill('[name="name"]','Pants');fill('[name="image"]','assets/category-shirts.webp');submit('[data-category-form]');const cat=S.getCategories().find(c=>c.name==='Pants');assert.ok(cat);assert.equal(cat.image,'assets/category-shirts.webp');click('[data-tab="subcategories"]');click('[data-action="add-category"]');fill('[name="name"]','Formal Pants');change('[name="categoryId"]',cat.id);submit('[data-category-form]');assert.ok(S.getSubcategories(cat.id).some(c=>c.name==='Formal Pants'))});
pass('Rename linked category without orphaning products',()=>{const cat=S.getCategories().find(c=>c.id==='cat-tshirts');S.saveCategory({...cat,name:'Tee Collection'});assert.equal(S.getProducts().find(p=>p.id===1).category,'Tee Collection');S.saveCategory({...cat,name:'T-Shirts'});assert.throws(()=>S.deleteCategory(cat.id,false),/Reassign/)});
pass('Create each role through Admin account form',()=>{for(const [tab,role] of [['staff-accounts','staff'],['management-accounts','management'],['b2b-accounts','b2b']]){click('[data-tab="'+tab+'"]');click('[data-action="new-account"]');assert.equal(find('[name="role"]').value,role);fill('[name="name"]','Test '+role);fill('[name="username"]','qa-'+role);fill('[name="password"]','password123');submit('[data-account-form]');assert.ok(S.authenticate(role,'qa-'+role,'password123'));}});
pass('Suspension and password reset revoke sessions',()=>{const a=S.getAccounts().find(a=>a.username==='qa-staff');S.saveAccount({...a,active:false});assert.equal(S.authenticate('staff','qa-staff','password123'),null);S.saveAccount({...a,active:true,password:'changed123'});assert.equal(S.authenticate('staff','qa-staff','password123'),null);assert.ok(S.authenticate('staff','qa-staff','changed123'));});
pass('Create/edit/disable cloth and print methods',()=>{click('[data-tab="fabrics"]');click('[data-config-new]');fill('[name="name"]','Linen');fill('[name="note"]','Light summer linen');fill('[name="price"]',25);submit('[data-config-form]');const f=S.getFabrics().find(f=>f.name==='Linen');assert.equal(f.price,25);click('[data-tab="custom"]');click('[data-config-new]');fill('[name="name"]','Test print');fill('[name="price"]',30);fill('[name="textPrice"]',20);submit('[data-config-form]');const m=S.getPrints().find(m=>m.name==='Test print');click('[data-config-edit="'+m.id+'"]');change('[name="active"]',false);submit('[data-config-form]');assert.equal(S.getPrints().find(m=>m.name==='Test print').active,false)});
pass('Customization config saves exact hex, cloth and print choices',()=>{click('[data-tab="customizable"]');click('[data-edit-custom="900"]');fill('[name="customColours"]','Brand Purple=#64116f\nWhite=#ffffff');find('[name="fabricIds"]').checked=true;submit('[data-product-form]');const p=S.getProducts().find(p=>String(p.id)==='900');assert.equal(p.customColorValues['Brand Purple'],'#64116f');assert.ok(p.allowedFabricIds.length)});
pass('Combined size and colour filters never mix different variants',()=>{const p={...base,active:true,available:true,variants:[{colour:'Blue',size:'6',stock:1,available:true},{colour:'Red',size:'7',stock:1,available:true},{colour:'Blue',size:'7',stock:0,available:true}]};assert.equal(S.matches(p,{sizes:['7'],colors:['Blue']}),false);assert.equal(S.matches(p,{sizes:['6','7'],colors:['Blue']}),true);assert.equal(S.matches(p,{sizes:['8']}),false);assert.equal(S.matches(p,{availability:'unavailable'}),false)});
pass('Keywords are searchable; variant barcode search is exact and internal',()=>{const p=S.getProducts().find(p=>p.id==='test-simple');assert.equal(S.matches(p,{},'v strap'),true);assert.equal(S.matches(p,{},'SLIM-001',true),true);assert.equal(S.matches(p,{},'SLIM-001',false),false)});
pass('One Option variant image resolution',()=>{let p=S.getProducts().find(p=>p.id==='test-simple');p.variants[0].image='assets/crew-tee.webp';p.variants[1].image='assets/polo-shirt.webp';p=S.saveProduct(p);assert.equal(S.productImage(p,'','front','Slim'),'assets/polo-shirt.webp')});
pass('Staff permissions, exact stock changes and oversell rejection',()=>{S.setSession(S.authenticate('staff','qa-staff','changed123'));const p=S.getProducts().find(p=>p.id==='test-simple'),v=p.variants[1];assert.equal(S.adjustStock(p.id,v.id,-1),4);assert.equal(S.adjustStock(p.id,v.id,5),9);assert.throws(()=>S.adjustStock(p.id,v.id,-100),/Not enough/);assert.throws(()=>S.saveProduct(p),/authorized/);assert.throws(()=>S.saveCategory({name:'Illegal'}),/authorized/);assert.equal(S.getProducts().find(p=>p.id==='test-simple').variants[0].stock,5)});
pass('Management can edit products but not accounts or categories',()=>{S.setSession(S.authenticate('management','manager','manager123'));const p=S.getProducts().find(p=>p.id==='test-simple');S.saveProduct({...p,description:'Managed'});assert.throws(()=>S.saveAccount({}),/authorized/);assert.throws(()=>S.saveCategory({name:'Illegal'}),/authorized/)});
const retail=page('index.html'),rw=retail.window,rd=rw.document;
pass('Customer catalogue, category and search render',()=>{rd.querySelector('[data-go="catalog"]').click();assert.equal(rd.querySelectorAll('.product-card').length,7);const search=rd.querySelector('[data-catalog-search]');search.value='Crew';search.dispatchEvent(new rw.Event('input'));assert.equal(rd.querySelectorAll('.product-card').length,1);rd.querySelector('.product-card').click();assert.ok(rd.querySelector('[data-action="buy-now"]'));assert.ok(!rd.querySelector('[data-design-layer]'));});
pass('Product options, gallery and enquiry message',()=>{rd.querySelector('[data-product-color="White"]').click();rd.querySelector('[data-product-size="M"]').click();let field=rd.querySelector('[data-product-quantity]');field.value='3';field.dispatchEvent(new rw.Event('input'));const text=new URL(rd.querySelector('[data-enquiry]').href).searchParams.get('text');assert.match(text,/White/);assert.match(text,/Quantity: 3/);assert.match(text,/OL-TEE-001/);assert.ok(rd.querySelectorAll('[data-gallery-src]').length>1)});
pass('Customer checkout reduces exact variant stock',()=>{rd.querySelector('[data-action="buy-now"]').click();const form=rd.querySelector('[data-checkout-form]');for(const [k,v] of Object.entries({name:'QA Customer',phone:'9000000000',address:'Local test address'}))form.querySelector('[name="'+k+'"]').value=v;rd.querySelector('[data-action="delivery-step"]').click();rd.querySelector('[data-action="submit-order"]').click();assert.match(rd.body.textContent,/Your order is saved/);const p=rw.OneLineStore.getProducts().find(p=>p.id===1);assert.equal(rw.OneLineStore.productStock(p,'White','M'),5)});
const b2b=page('b2b.html','b2b'),bd=b2b.window.document;
pass('B2B listing, detail and route guards have no prices or checkout',()=>{assert.ok(!/[₹%]|MRP|discount/i.test(bd.body.textContent));assert.equal(bd.querySelectorAll('[data-go="cart"],[data-go="checkout"],[data-go="customize"]').length,0);bd.querySelector('.product-card').click();assert.ok(!/₹|MRP|discount/i.test(bd.body.textContent));assert.ok(!bd.querySelector('[data-action="buy-now"]'));assert.match(new URL(bd.querySelector('[data-enquiry]').href).searchParams.get('text'),/wholesale\/B2B price/);b2b.window.dispatchEvent(new b2b.window.PopStateEvent('popstate',{state:{screen:'checkout'}}));assert.ok(!/₹/.test(bd.body.textContent));assert.ok(!bd.querySelector('[data-checkout-form]'));});
const staff=page('staff.html','staff'),sd=staff.window.document;
pass('Staff portal only has stock operations and barcode search',()=>{assert.ok(!sd.querySelector('[data-action="new-product"]'));let field=sd.querySelector('[data-stock-search]');field.value='890100000001';field.dispatchEvent(new staff.window.Event('input'));assert.equal(sd.querySelectorAll('.stock-product').length,1);sd.querySelector('[data-stock-delta="-1"]').click();assert.match(sd.body.textContent,/New stock: 7/);const qty=sd.querySelector('[data-stock-qty]');qty.value='5';sd.querySelector('[data-stock-delta="1"]').click();assert.match(sd.body.textContent,/New stock: 12/)});
const manager=page('management.html','management');pass('Management uses shared editor without system tabs',()=>{const md=manager.window.document;assert.equal(md.querySelectorAll('[data-tab="users"],[data-tab="catalog"],[data-tab="settings"]').length,0);md.querySelector('[data-action="new-product"]').click();assert.ok(md.querySelector('[data-ready-product-form]'));});
for(const x of [dom,retail,b2b,staff,manager])x.window.close();
assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync('qa/flow-results.json',JSON.stringify(results,null,2));console.log(results.map(r=>r.status+' '+r.name).join('\n'));
