const {page,errors}=require('./smoke.cjs');const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path'),{JSDOM,VirtualConsole}=require('jsdom');const results=[];const check=(name,fn)=>{fn();results.push({name,status:'PASS'});};
check('Every HTML entry has valid local scripts, styles, manifest and icons',()=>{for(const file of fs.readdirSync('project').filter(f=>f.endsWith('.html'))){const doc=new JSDOM(fs.readFileSync('project/'+file,'utf8')).window.document;for(const el of doc.querySelectorAll('script[src],link[href]')){const ref=el.getAttribute('src')||el.getAttribute('href');if(!/^https?:/.test(ref))assert.ok(fs.existsSync(path.join('project',ref.split('?')[0])),ref);}assert.ok(doc.querySelector('meta[name="viewport"]'));}});
check('CSS stylesheets parse including responsive overrides',()=>{let issues=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>issues.push(e.message));const dom=new JSDOM('<html><head></head><body></body></html>',{virtualConsole:vc});for(const f of ['styles.css','upgrade.css']){const style=dom.window.document.createElement('style');style.textContent=fs.readFileSync('project/css/'+f,'utf8');dom.window.document.head.append(style);assert.ok(style.sheet.cssRules.length>0);}assert.equal(issues.length,0,issues.join('\n'));dom.window.close();});
check('Fresh service worker core resolves every local file',()=>{const source=fs.readFileSync('project/sw.js','utf8');const CORE=JSON.parse(source.split('const CORE=')[1].split(';\n')[0]);for(const file of CORE)assert.ok(fs.existsSync(path.join('project',file.split('?')[0])),file);for(const file of ['admin.html','staff.html','management.html','b2b.html','receiver.html'])assert.ok(CORE.includes('./'+file));assert.match(source,/one-line-static-20260915-r7/);assert.ok(!source.includes('1750-r4'));});
check('Cache activation deletes older app caches and preserves unrelated caches',()=>{const src=fs.readFileSync('project/sw.js','utf8');assert.match(src,/name!==CACHE/);assert.match(src,/name.startsWith\('one-line-'\)/);assert.match(src,/name.startsWith\('custom-store-'\)/);});
check('Product ratios are 3:4 and category images stay square in release CSS',()=>{const css=fs.readFileSync('project/css/upgrade.css','utf8');assert.match(css,/\.product-card \.product-image-wrap\{aspect-ratio:3\/4!important/);assert.match(css,/\.category-photo\{aspect-ratio:1!important/);assert.match(css,/object-fit:contain!important/);});
check('No stale CSS or JS version in entry pages',()=>{for(const file of fs.readdirSync('project').filter(f=>f.endsWith('.html'))){const html=fs.readFileSync('project/'+file,'utf8');assert.ok(!html.includes('1750-r4'));for(const match of html.matchAll(/(?:src|href)="((?:js\/|css\/)[^"]+)"/g))assert.ok(match[1].endsWith('?v=20260915-r7'));}});
const admin=page('admin.html','admin'),S=admin.window.OneLineStore;
check('Missing variants cannot fall back to aggregate stock',()=>{const p=S.getProducts()[0];assert.equal(S.productStock(p,'Missing','M'),0);assert.equal(S.productStock(p,'Black','Missing'),0);});
check('An order with multiple lines cannot oversell a single variant',()=>{const p=S.getProducts()[0],v=p.variants[0];const item={productId:p.id,color:v.colour,size:v.size,qty:5,price:100};const before=S.getOrders().length;assert.throws(()=>S.commitOrder({orderItems:[item,item]},{role:'customer'}),/Stock changed/);assert.equal(S.getOrders().length,before);assert.equal(S.getProducts()[0].variants[0].stock,v.stock);});
check('Suspended active staff session is rejected immediately',()=>{const account=S.authenticate('staff','staff','staff123');S.setSession(account);const rows=S.getAccounts();rows.find(x=>x.id===account.id).active=false;admin.window.localStorage.setItem(S.KEYS.accounts,JSON.stringify(rows));assert.equal(S.getSession('staff'),null);assert.throws(()=>S.adjustStock(1,'black-s',-1),/authorized/);});
check('Legacy aggregate inventory migration preserves totals and custom-model removal',()=>{const products=S.getProducts();assert.equal(products.find(p=>p.id===5).stock,60);assert.equal(products.find(p=>p.id===6).stock,100);assert.equal(products.find(p=>p.id===7).stock,23);admin.window.localStorage.setItem(S.KEYS.products,JSON.stringify(products.filter(p=>!p.customSection)));assert.equal(S.getProducts().filter(p=>p.customSection).length,0);});
// Receiver uses the old production UI, now behind an admin login.
const receiver=page('staff.html');receiver.window.OneLineStore.setSession(receiver.window.OneLineStore.authenticate('admin','admin','admin123'));receiver.window.eval(fs.readFileSync('project/js/receiver.js','utf8'));
check('Order receiving compatibility route: order board and detailed order drawer',()=>{const d=receiver.window.document;assert.ok(d.querySelector('.order-board'));d.querySelector('[data-order]').click();assert.ok(d.querySelector('.order-drawer'));assert.ok(d.querySelector('[data-status="Packed"]'));d.querySelector('[data-status="Packed"]').click();assert.equal(receiver.window.OneLineStore.getOrders()[0].status,'Packed');});
check('Order receiving still supports direct orders',()=>{const d=receiver.window.document;d.querySelector('[data-action="close-order"]').click();d.querySelector('[data-tab="direct"]').click();d.querySelector('[data-add-direct]').click();assert.equal(d.querySelectorAll('.direct-items article').length,1);const form=d.querySelector('[data-direct-order]');for(const [k,v]of Object.entries({customer:'QA buyer',phone:'9000000000',address:'Local test'}))form.querySelector('[name="'+k+'"]').value=v;form.dispatchEvent(new receiver.window.Event('submit',{bubbles:true,cancelable:true}));assert.equal(receiver.window.OneLineStore.getOrders()[0].customer,'QA buyer');});
assert.equal(errors.length,0,errors.join('\n'));for(const dom of [admin,receiver])dom.window.close();fs.writeFileSync('qa/release-results.json',JSON.stringify(results,null,2));console.log(results.map(r=>r.status+' '+r.name).join('\n'));
