const {page,errors}=require('./smoke.cjs'),assert=require('node:assert/strict'),fs=require('fs'),{createCanvas,Image}=require('@napi-rs/canvas');
const results=[];function canvasSupport(w){w.Image=Image;w.HTMLCanvasElement.prototype.getContext=function(type){if(!this._canvas)this._canvas=createCanvas(this.width,this.height);return this._canvas.getContext(type);};w.HTMLCanvasElement.prototype.toDataURL=function(type,q){return this._canvas.toDataURL(type,q);};}
async function main(){
const admin=page('admin.html','admin'),w=admin.window,d=w.document,S=w.OneLineStore;canvasSupport(w);
const fixture=fs.readFileSync('project/icon-512.png'),file=new w.File([fixture],'test-logo.png',{type:'image/png'});
const compressed=await S.compressImage(file,128,.84);assert.match(compressed,/^data:image\/webp;base64,/);const im=new Image();im.src=Buffer.from(compressed.split(',')[1],'base64');await new Promise(r=>setTimeout(r,20));assert.ok(im.width<=128);results.push({name:'Real image decoding, resizing and WebP compression using native canvas',status:'PASS'});
const change=(sel,v)=>{const e=d.querySelector(sel);e.value=v;e.dispatchEvent(new w.Event('change',{bubbles:true}));};const fill=(sel,v)=>d.querySelector(sel).value=v;
const upload=async(sel)=>{const input=d.querySelector(sel);assert.ok(input,sel);Object.defineProperty(input,'files',{value:[file],configurable:true});input.dispatchEvent(new w.Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,120));};
d.querySelector('[data-action="new-product"]').click();change('[name="categoryId"]','cat-tshirts');fill('[name="name"]','Upload Test');fill('[name="sku"]','UPLOAD-TEST');change('[name="productType"]','option');fill('[data-group-values]','Small, Large');fill('[data-group-qty]',3);await upload('[data-group-image]');assert.equal(d.querySelector('[data-group-values]').value,'Small, Large');d.querySelector('[data-add-group]').click();await upload('[data-images]');await upload('[data-variant-image]');d.querySelector('[data-ready-product-form]').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));let p=S.getProducts().find(p=>p.sku==='UPLOAD-TEST');assert.ok(p);assert.match(p.image,/^data:image\/webp/);assert.equal(p.variants.length,2);assert.match(p.variants[0].image,/^data:image\/webp/);assert.match(p.variants[1].image,/^data:image\/webp/);results.push({name:'Main and variant file uploads, option image inheritance, form save and persistence',status:'PASS'});
d.querySelector('[data-tab="catalog"]').click();d.querySelector('[data-action="add-category"]').click();fill('[name="name"]','Uploaded category');await upload('[data-entity-image]');d.querySelector('[data-category-form]').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.match(S.getCategories().find(c=>c.name==='Uploaded category').image,/^data:image\/webp/);results.push({name:'Category image upload and saved preview source',status:'PASS'});
const retail=page('index.html'),rw=retail.window,rd=rw.document;canvasSupport(rw);rd.querySelector('[data-go="customize"]').click();const fi=new rw.File([fixture],'art.png',{type:'image/png'}),inp=rd.querySelector('[data-file]');Object.defineProperty(inp,'files',{value:[fi],configurable:true});inp.dispatchEvent(new rw.Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,150));assert.equal(rd.querySelectorAll('[data-design-layer].image-layer').length,1);const src=rd.querySelector('[data-layer-content]').src;assert.match(src,/^data:image\/webp/);rd.querySelector('[data-action="add"]').click();assert.match(rw.OneLineStore.getCart()[0].customDesign.surfaceDesigns.front.layers[0].src,/^data:image\/webp/);results.push({name:'Customizer artwork file upload, canvas conversion and saved artwork data',status:'PASS'});
assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync('qa/upload-results.json',JSON.stringify(results,null,2));console.log(results);admin.window.close();retail.window.close();
}
main().catch(e=>{console.error(e);process.exitCode=1});
